.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-registry-admin-signer-add 1  "add " 
.SH NAME
start\-registry\-admin\-signer\-add \- Add signer
.SH SYNOPSIS
\fBstart\-registry admin signer add\fR <\fB\-n\fR|\fB\-\-name\fR> [\fB\-c\fR|\fB\-\-contact\fR] [\fB\-\-key\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIDATABASE\fR] 
.SH DESCRIPTION
Add signer
.SH OPTIONS
.TP
\fB\-n\fR, \fB\-\-name\fR \fI<NAME>\fR
Name of the signer
.TP
\fB\-c\fR, \fB\-\-contact\fR \fI<CONTACT>\fR
Contact information for signer
.TP
\fB\-\-key\fR \fI<KEYS>\fR
Public key for signer
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIDATABASE\fR]
Path to the database file
