.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-registry-info-set-name 1  "set-name " 
.SH NAME
start\-registry\-info\-set\-name \- Set the registry name
.SH SYNOPSIS
\fBstart\-registry info set\-name\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Set the registry name
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>
Name of the registry
