.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-registry-admin 1  "admin " 
.SH NAME
start\-registry\-admin \- Commands to add or list admins or signers
.SH SYNOPSIS
\fBstart\-registry admin\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Commands to add or list admins or signers
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-registry\-admin\-add(1)
Add admin signer
.TP
start\-registry\-admin\-list(1)
List admin signers
.TP
start\-registry\-admin\-remove(1)
Remove admin signer
.TP
start\-registry\-admin\-signer(1)
Commands to add or list signers
