.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-registry-package-category-add-package 1  "add-package " 
.SH NAME
start\-registry\-package\-category\-add\-package \- Add a package to a category
.SH SYNOPSIS
\fBstart\-registry package category add\-package\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR> <\fIPACKAGE\fR> 
.SH DESCRIPTION
Add a package to a category
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>

.TP
<\fIPACKAGE\fR>

