.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-registry-os-version-remove 1  "remove " 
.SH NAME
start\-registry\-os\-version\-remove \- Remove OS version
.SH SYNOPSIS
\fBstart\-registry os version remove\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIVERSION\fR> 
.SH DESCRIPTION
Remove OS version
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIVERSION\fR>
StartOS version number
