import { IST } from '@start9labs/start-sdk'

export const wifiSpec: IST.ValueSpecObject = {
  type: 'object',
  name: 'WiFi Credentials',
  description: null,
  warning: null,
  spec: {
    ssid: {
      type: 'text',
      minLength: null,
      maxLength: null,
      patterns: [],
      name: 'Network SSID',
      description: null,
      inputmode: 'text',
      placeholder: null,
      required: true,
      masked: false,
      default: null,
      warning: null,
      disabled: false,
      immutable: false,
      generate: null,
    },
    password: {
      type: 'text',
      minLength: null,
      maxLength: null,
      patterns: [],
      name: 'Password',
      description: null,
      inputmode: 'text',
      placeholder: null,
      required: true,
      masked: true,
      default: null,
      warning: null,
      disabled: false,
      immutable: false,
      generate: null,
    },
  },
}
