.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-registry-metrics-users 1  "users " 
.SH NAME
start\-cli\-registry\-metrics\-users \- Count unique active users within a time range
.SH SYNOPSIS
\fBstart\-cli registry metrics users\fR [\fB\-\-after\fR] [\fB\-\-before\fR] [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Count unique active users within a time range
.SH OPTIONS
.TP
\fB\-\-after\fR \fI<AFTER>\fR
Start of time range (RFC 3339 timestamp)
.TP
\fB\-\-before\fR \fI<BEFORE>\fR
End of time range (RFC 3339 timestamp)
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
