.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-wifi-set-enabled 1  "set-enabled " 
.SH NAME
start\-cli\-wifi\-set\-enabled \- Enable or disable wifi
.SH SYNOPSIS
\fBstart\-cli wifi set\-enabled\fR [\fB\-\-enabled\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Enable or disable wifi
.SH OPTIONS
.TP
\fB\-\-enabled\fR
Enable or disable WiFi
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
