.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-tunnel-subnet-remove 1  "remove " 
.SH NAME
start\-cli\-tunnel\-subnet\-remove \- Remove a subnet
.SH SYNOPSIS
\fBstart\-cli tunnel subnet remove\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Remove a subnet
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
