.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-net-gateway-set-default-outbound 1  "set-default-outbound " 
.SH NAME
start\-cli\-net\-gateway\-set\-default\-outbound \- Set the default outbound gateway
.SH SYNOPSIS
\fBstart\-cli net gateway set\-default\-outbound\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIGATEWAY\fR] 
.SH DESCRIPTION
Set the default outbound gateway
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIGATEWAY\fR]
Gateway identifier
