.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-tunnel-update-check 1  "check " 
.SH NAME
start\-cli\-tunnel\-update\-check \- Check for available updates
.SH SYNOPSIS
\fBstart\-cli tunnel update check\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Check for available updates
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
