.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-s9pk-inspect-cat 1  "cat " 
.SH NAME
start\-cli\-s9pk\-inspect\-cat \- Display file contents from s9pk
.SH SYNOPSIS
\fBstart\-cli s9pk inspect cat\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIFILE_PATH\fR> 
.SH DESCRIPTION
Display file contents from s9pk
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFILE_PATH\fR>
Path to the file
