.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-registry-os-version-signer-list 1  "list " 
.SH NAME
start\-cli\-registry\-os\-version\-signer\-list \- List version signers
.SH SYNOPSIS
\fBstart\-cli registry os version signer list\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIVERSION\fR> 
.SH DESCRIPTION
List version signers
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIVERSION\fR>

