.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-tunnel-web-get-certificate 1  "get-certificate " 
.SH NAME
start\-cli\-tunnel\-web\-get\-certificate \- Get the certificate for the webserver
.SH SYNOPSIS
\fBstart\-cli tunnel web get\-certificate\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Get the certificate for the webserver
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
