.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-tunnel-auth-key-add 1  "add " 
.SH NAME
start\-cli\-tunnel\-auth\-key\-add \- Add a new authorized key
.SH SYNOPSIS
\fBstart\-cli tunnel auth key add\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> <\fIKEY\fR> 
.SH DESCRIPTION
Add a new authorized key
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>

.TP
<\fIKEY\fR>

