.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-package-action-get-input 1  "get-input " 
.SH NAME
start\-cli\-package\-action\-get\-input \- Get action input specification
.SH SYNOPSIS
\fBstart\-cli package action get\-input\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIPACKAGE_ID\fR> <\fIACTION_ID\fR> 
.SH DESCRIPTION
Get action input specification
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPACKAGE_ID\fR>
Package identifier
.TP
<\fIACTION_ID\fR>
Action identifier
