.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-package-start 1  "start " 
.SH NAME
start\-cli\-package\-start \- Start a service
.SH SYNOPSIS
\fBstart\-cli package start\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR> 
.SH DESCRIPTION
Start a service
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>
Package identifier
