.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-s9pk-edit-manifest 1  "manifest " 
.SH NAME
start\-cli\-s9pk\-edit\-manifest \- Edit s9pk manifest
.SH SYNOPSIS
\fBstart\-cli s9pk edit manifest\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIEXPRESSION\fR> 
.SH DESCRIPTION
Edit s9pk manifest
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIEXPRESSION\fR>
Database patch expression to apply
