.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-tunnel-auth-set-password 1  "set-password " 
.SH NAME
start\-cli\-tunnel\-auth\-set\-password \- Set user interface password
.SH SYNOPSIS
\fBstart\-cli tunnel auth set\-password\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Set user interface password
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
