.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-server-host-address-domain-private-remove 1  "remove " 
.SH NAME
start\-cli\-server\-host\-address\-domain\-private\-remove \- Remove private domain from host
.SH SYNOPSIS
\fBstart\-cli server host address domain private remove\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIFQDN\fR> 
.SH DESCRIPTION
Remove private domain from host
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFQDN\fR>
Fully qualified domain name
