.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-notification-mark-seen 1  "mark-seen " 
.SH NAME
start\-cli\-notification\-mark\-seen \- Mark notifications as seen
.SH SYNOPSIS
\fBstart\-cli notification mark\-seen\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIIDS\fR] 
.SH DESCRIPTION
Mark notifications as seen
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIIDS\fR]
Notification IDs
