.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-net-dns-query 1  "query " 
.SH NAME
start\-cli\-net\-dns\-query \- Test DNS configuration for a domain
.SH SYNOPSIS
\fBstart\-cli net dns query\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIFQDN\fR> 
.SH DESCRIPTION
Test DNS configuration for a domain
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFQDN\fR>
Fully qualified domain name
