.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-notification-mark-unseen 1  "mark-unseen " 
.SH NAME
start\-cli\-notification\-mark\-unseen \- Mark notifications as unseen
.SH SYNOPSIS
\fBstart\-cli notification mark\-unseen\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIIDS\fR] 
.SH DESCRIPTION
Mark notifications as unseen
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIIDS\fR]
Notification IDs
