.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-package-host-address 1  "address " 
.SH NAME
start\-cli\-package\-host\-address \- Commands for managing host addresses
.SH SYNOPSIS
\fBstart\-cli package host address\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIHOST\fR> <\fIsubcommands\fR>
.SH DESCRIPTION
Commands for managing host addresses
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIHOST\fR>
Host identifier
.SH SUBCOMMANDS
.TP
start\-cli\-package\-host\-address\-domain(1)
Commands for managing host address domains
.TP
start\-cli\-package\-host\-address\-list(1)
List addresses for a host
