.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-net-acme-remove 1  "remove " 
.SH NAME
start\-cli\-net\-acme\-remove \- Remove ACME certificate acquisition configuration
.SH SYNOPSIS
\fBstart\-cli net acme remove\fR <\fB\-\-provider\fR> [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Remove ACME certificate acquisition configuration
.SH OPTIONS
.TP
\fB\-\-provider\fR \fI<PROVIDER>\fR
ACME provider identifier or url
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
