.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-registry-info-set-icon 1  "set-icon " 
.SH NAME
start\-registry\-info\-set\-icon \- Set the registry icon
.SH SYNOPSIS
\fBstart\-registry info set\-icon\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIICON\fR> 
.SH DESCRIPTION
Set the registry icon
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIICON\fR>
Icon source: file path, file:// URL, http(s):// URL, or data: URL
