.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-registry-os-promote 1  "promote " 
.SH NAME
start\-registry\-os\-promote \- Promote an OS version from one registry to another
.SH SYNOPSIS
\fBstart\-registry os promote\fR [\fB\-\-from\fR] [\fB\-\-to\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIVERSION\fR> 
.SH DESCRIPTION
Promote an OS version from one registry to another
.SH OPTIONS
.TP
\fB\-\-from\fR \fI<FROM>\fR
Source registry URL to promote from
.TP
\fB\-\-to\fR \fI<TO>\fR
Destination registry URL to promote to
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIVERSION\fR>
StartOS version number
