.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-registry-os-version-add 1  "add " 
.SH NAME
start\-registry\-os\-version\-add \- Add OS version
.SH SYNOPSIS
\fBstart\-registry os version add\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIVERSION\fR> <\fIHEADLINE\fR> <\fIRELEASE_NOTES\fR> <\fISOURCE_VERSION\fR> 
.SH DESCRIPTION
Add OS version
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIVERSION\fR>
StartOS version number
.TP
<\fIHEADLINE\fR>
Short headline for the version
.TP
<\fIRELEASE_NOTES\fR>
Release notes for this version
.TP
<\fISOURCE_VERSION\fR>
Source version range for migration
