.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-registry-package-remove-mirror 1  "remove-mirror " 
.SH NAME
start\-cli\-registry\-package\-remove\-mirror \- Remove mirror package
.SH SYNOPSIS
\fBstart\-cli registry package remove\-mirror\fR <\fB\-\-url\fR> [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR> <\fIVERSION\fR> 
.SH DESCRIPTION
Remove mirror package
.SH OPTIONS
.TP
\fB\-\-url\fR \fI<URL>\fR
URL of the mirror
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>
Package identifier
.TP
<\fIVERSION\fR>
Package version
