.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-registry-admin-signer-remove 1  "remove " 
.SH NAME
start\-cli\-registry\-admin\-signer\-remove \- Remove signer and all their authorizations
.SH SYNOPSIS
\fBstart\-cli registry admin signer remove\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR> 
.SH DESCRIPTION
Remove signer and all their authorizations
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>
Signer identifier
