.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-net-gateway-check-port 1  "check-port " 
.SH NAME
start\-cli\-net\-gateway\-check\-port \- Check if a port is reachable from the WAN
.SH SYNOPSIS
\fBstart\-cli net gateway check\-port\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIPORT\fR> <\fIGATEWAY\fR> 
.SH DESCRIPTION
Check if a port is reachable from the WAN
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPORT\fR>
Port number
.TP
<\fIGATEWAY\fR>
Gateway identifier
