.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-util 1  "util " 
.SH NAME
start\-cli\-util \- Command for calculating the blake3 hash of a file
.SH SYNOPSIS
\fBstart\-cli util\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Command for calculating the blake3 hash of a file
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-cli\-util\-b3sum(1)
Calculate blake3 hash for a file
