.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-server-shutdown 1  "shutdown " 
.SH NAME
start\-cli\-server\-shutdown \- Shutdown the server
.SH SYNOPSIS
\fBstart\-cli server shutdown\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Shutdown the server
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
