.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-registry-package-category-add 1  "add " 
.SH NAME
start\-cli\-registry\-package\-category\-add \- Add a category to the registry
.SH SYNOPSIS
\fBstart\-cli registry package category add\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR> <\fINAME\fR> 
.SH DESCRIPTION
Add a category to the registry
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>

.TP
<\fINAME\fR>

