.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-registry-os-asset 1  "asset " 
.SH NAME
start\-cli\-registry\-os\-asset \- Commands to add, sign, or get registry assets
.SH SYNOPSIS
\fBstart\-cli registry os asset\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Commands to add, sign, or get registry assets
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-cli\-registry\-os\-asset\-add(1)
Add asset to registry
.TP
start\-cli\-registry\-os\-asset\-get(1)
Commands to download image, iso, or squashfs files
.TP
start\-cli\-registry\-os\-asset\-remove(1)
.TP
start\-cli\-registry\-os\-asset\-sign(1)
Sign file and add to registry
