.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-package-host 1  "host " 
.SH NAME
start\-cli\-package\-host \- Manage network hosts for a package
.SH SYNOPSIS
\fBstart\-cli package host\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIPACKAGE\fR> <\fIsubcommands\fR>
.SH DESCRIPTION
Manage network hosts for a package
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPACKAGE\fR>
Package identifier
.SH SUBCOMMANDS
.TP
start\-cli\-package\-host\-address(1)
Commands for managing host addresses
.TP
start\-cli\-package\-host\-binding(1)
Commands for managing host bindings
