.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-server-set-echoip-urls 1  "set-echoip-urls " 
.SH NAME
start\-cli\-server\-set\-echoip\-urls \- Set the Echo IP service URLs
.SH SYNOPSIS
\fBstart\-cli server set\-echoip\-urls\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIURLS\fR] 
.SH DESCRIPTION
Set the Echo IP service URLs
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIURLS\fR]
Echo IP service URLs for external IP detection
