.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-net-dns-dump-table 1  "dump-table " 
.SH NAME
start\-cli\-net\-dns\-dump\-table \- Dump address resolution table
.SH SYNOPSIS
\fBstart\-cli net dns dump\-table\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Dump address resolution table
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
