.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-package-uninstall 1  "uninstall " 
.SH NAME
start\-cli\-package\-uninstall \- Remove a package
.SH SYNOPSIS
\fBstart\-cli package uninstall\fR [\fB\-\-soft\fR] [\fB\-\-force\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR> 
.SH DESCRIPTION
Remove a package
.SH OPTIONS
.TP
\fB\-\-soft\fR
Uninstall without deleting service data
.TP
\fB\-\-force\fR
Ignore errors in service uninit script
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>
Package identifier
