.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-server-rebuild 1  "rebuild " 
.SH NAME
start\-cli\-server\-rebuild \- Teardown and rebuild containers
.SH SYNOPSIS
\fBstart\-cli server rebuild\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Teardown and rebuild containers
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
