.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-package-install 1  "install " 
.SH NAME
start\-cli\-package\-install \- Install a package
.SH SYNOPSIS
\fBstart\-cli package install\fR [\fB\-s\fR|\fB\-\-sideload\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIID\fR] [\fIVERSION\fR] 
.SH DESCRIPTION
Install a package
.SH OPTIONS
.TP
\fB\-s\fR, \fB\-\-sideload\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIID\fR]
Package identifier
.TP
[\fIVERSION\fR]
Version range constraint
