.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-registry-package-signer 1  "signer " 
.SH NAME
start\-cli\-registry\-package\-signer \- Add, remove, and list package signers
.SH SYNOPSIS
\fBstart\-cli registry package signer\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Add, remove, and list package signers
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-cli\-registry\-package\-signer\-add(1)
Add package signer
.TP
start\-cli\-registry\-package\-signer\-list(1)
List package signers
.TP
start\-cli\-registry\-package\-signer\-remove(1)
Remove package signer
