.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-net-forward 1  "forward " 
.SH NAME
start\-cli\-net\-forward \- Manage port forwards
.SH SYNOPSIS
\fBstart\-cli net forward\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Manage port forwards
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-cli\-net\-forward\-dump\-table(1)
Dump port forward table
