.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-package-restart 1  "restart " 
.SH NAME
start\-cli\-package\-restart \- Restart a service
.SH SYNOPSIS
\fBstart\-cli package restart\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR> 
.SH DESCRIPTION
Restart a service
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>
Package identifier
