.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-server-time 1  "time " 
.SH NAME
start\-cli\-server\-time \- Display server time and uptime
.SH SYNOPSIS
\fBstart\-cli server time\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Display server time and uptime
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
