.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-util-b3sum 1  "b3sum " 
.SH NAME
start\-cli\-util\-b3sum \- Calculate blake3 hash for a file
.SH SYNOPSIS
\fBstart\-cli util b3sum\fR [\fB\-\-no\-mmap\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIFILE\fR> 
.SH DESCRIPTION
Calculate blake3 hash for a file
.SH OPTIONS
.TP
\fB\-\-no\-mmap\fR
Disable memory\-mapped file I/O
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFILE\fR>

