.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-registry-package-signer-remove 1  "remove " 
.SH NAME
start\-cli\-registry\-package\-signer\-remove \- Remove package signer
.SH SYNOPSIS
\fBstart\-cli registry package signer remove\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR> <\fISIGNER\fR> 
.SH DESCRIPTION
Remove package signer
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>
Package identifier
.TP
<\fISIGNER\fR>
Signer identifier
