.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-server-clear-smtp 1  "clear-smtp " 
.SH NAME
start\-cli\-server\-clear\-smtp \- Remove system smtp server and credentials
.SH SYNOPSIS
\fBstart\-cli server clear\-smtp\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Remove system smtp server and credentials
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
