.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-s9pk-inspect-manifest 1  "manifest " 
.SH NAME
start\-cli\-s9pk\-inspect\-manifest \- Display the s9pk manifest
.SH SYNOPSIS
\fBstart\-cli s9pk inspect manifest\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Display the s9pk manifest
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
