.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-s9pk-inspect-file-tree 1  "file-tree " 
.SH NAME
start\-cli\-s9pk\-inspect\-file\-tree \- Display list of paths in s9pk
.SH SYNOPSIS
\fBstart\-cli s9pk inspect file\-tree\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Display list of paths in s9pk
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
