import { ChangeDetectionStrategy, Component } from '@angular/core'
import { FormControl } from '@angular/forms'
import {
  ActionSheetController,
  AlertController,
  ModalController,
  ToastController,
} from '@ionic/angular'

// TODO: Turn into DI token if this is needed someplace else too
const ICONS = [
  'add',
  'alert-outline',
  'alert-circle-outline',
  'aperture-outline',
  'arrow-back',
  'arrow-forward',
  'arrow-up',
  'briefcase-outline',
  'brush-outline',
  'bookmark-outline',
  'cellular-outline',
  'chatbubbles-outline',
  'checkmark',
  'chevron-down',
  'chevron-up',
  'chevron-forward',
  'close',
  'close-circle-outline',
  'cloud-outline',
  'cloud-done',
  'cloud-done-outline',
  'cloud-download-outline',
  'cloud-offline-outline',
  'cloud-upload-outline',
  'code-outline',
  'color-wand-outline',
  'construct-outline',
  'copy-outline',
  'desktop-outline',
  'download-outline',
  'duplicate-outline',
  'earth-outline',
  'ellipsis-horizontal',
  'eye-off-outline',
  'eye-outline',
  'file-tray-stacked-outline',
  'finger-print',
  'flash-outline',
  'folder-open-outline',
  'globe-outline',
  'grid-outline',
  'help-circle-outline',
  'hammer-outline',
  'information-circle-outline',
  'key-outline',
  'list-outline',
  'log-out-outline',
  'logo-bitcoin',
  'mail-outline',
  'map-outline',
  'medkit-outline',
  'notifications-outline',
  'open-outline',
  'options-outline',
  'pencil',
  'phone-portrait-outline',
  'play-outline',
  'power',
  'pricetag-outline',
  'pulse',
  'push-outline',
  'qr-code-outline',
  'receipt-outline',
  'refresh',
  'reload',
  'reload-circle-outline',
  'remove',
  'remove-circle-outline',
  'remove-outline',
  'repeat-outline',
  'ribbon-outline',
  'rocket-outline',
  'save-outline',
  'settings-outline',
  'shield-checkmark-outline',
  'stop-outline',
  'storefront-outline',
  'swap-vertical',
  'terminal-outline',
  'trash',
  'trash-outline',
  'warning-outline',
  'wifi',
]

const TAIGA = [
  'tuiIconPaintOutline',
  'tuiIconTrash',
  'tuiIconTrashOutline',
  'tuiIconChevronDown',
  'tuiIconChevronDownOutline',
  'tuiIconRefreshCcw',
  'tuiIconRefreshCcwOutline',
  'tuiIconEye',
  'tuiIconEyeOutline',
  'tuiIconEyeOff',
  'tuiIconEyeOffOutline',
  'tuiIconPlus',
  'tuiIconMinus',
  'tuiIconCheck',
  'tuiIconClose',
  'tuiIconCalendarLarge',
  'tuiIconHelpCircle',
]

@Component({
  selector: 'section[appPreloader]',
  templateUrl: 'preloader.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PreloaderComponent {
  readonly icons = ICONS
  readonly taiga = TAIGA
  readonly control = new FormControl()

  constructor(
    _modals: ModalController,
    _alerts: AlertController,
    _toasts: ToastController,
    _actions: ActionSheetController,
  ) {}
}
