use color_eyre::eyre::eyre;

use crate::notifications::{NotificationLevel, notify};
use crate::service::effects::prelude::*;

#[derive(Debug, Clone, Serialize, Deserialize, TS)]
#[ts(export)]
#[serde(rename_all = "camelCase")]
pub struct CreateNotificationParams {
    pub level: NotificationLevel,
    pub title: String,
    pub message: String,
    /// Notification code. `0` is a plain notification (no data); `2` carries
    /// a long-form, markdown-compatible body that the UI renders in a
    /// "View Details" modal. `1` is reserved for backup-report notifications
    /// generated by StartOS.
    #[ts(type = "0 | 2")]
    pub code: u32,
    /// Notification data. Shape depends on `code`: must be `null`/omitted for
    /// code `0`; must be a markdown-formatted string for code `2`.
    #[serde(default)]
    #[ts(optional, type = "string | null")]
    pub data: Option<String>,
}

pub async fn create(
    context: EffectContext,
    CreateNotificationParams {
        level,
        title,
        message,
        code,
        data,
    }: CreateNotificationParams,
) -> Result<(), Error> {
    let context = context.deref()?;
    let package_id = context.seed.id.clone();

    context
        .seed
        .ctx
        .db
        .mutate(move |db| match (code, data) {
            (0, None) => notify(db, Some(package_id), level, title, message, ()),
            (0, Some(_)) => Err(Error::new(
                eyre!("notification code 0 must not include data"),
                ErrorKind::InvalidRequest,
            )),
            (2, Some(data)) => notify(db, Some(package_id), level, title, message, data),
            (2, None) => Err(Error::new(
                eyre!("notification code 2 requires string data"),
                ErrorKind::InvalidRequest,
            )),
            (1, _) => Err(Error::new(
                eyre!("notification code 1 is reserved for backup-report notifications"),
                ErrorKind::InvalidRequest,
            )),
            (c, _) => Err(Error::new(
                eyre!("unsupported notification code: {c}"),
                ErrorKind::InvalidRequest,
            )),
        })
        .await
        .result?;
    Ok(())
}
