.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-container-action-get-input 1  "get-input " 
.SH NAME
start\-container\-action\-get\-input
.SH SYNOPSIS
\fBstart\-container action get\-input\fR [\fB\-p\fR|\fB\-\-package\-id\fR] [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIACTION_ID\fR> 
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-p\fR, \fB\-\-package\-id\fR \fI<PACKAGE_ID>\fR
Package identifier
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIACTION_ID\fR>
Action identifier
