.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-container-pipe-wrap 1  "pipe-wrap " 
.SH NAME
start\-container\-pipe\-wrap
.SH SYNOPSIS
\fBstart\-container pipe\-wrap\fR [\fB\-h\fR|\fB\-\-help\fR] [\fICOMMAND\fR] 
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fICOMMAND\fR]
Command to execute in the container
