.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-container-set-main-status 1  "set-main-status " 
.SH NAME
start\-container\-set\-main\-status
.SH SYNOPSIS
\fBstart\-container set\-main\-status\fR [\fB\-h\fR|\fB\-\-help\fR] <\fISTATUS\fR> 
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISTATUS\fR>

