.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-container 1  "start-container 0.4.0-alpha.21" 
.SH NAME
start\-container
.SH SYNOPSIS
\fBstart\-container\fR [\fB\-\-socket\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-\-socket\fR \fI<SOCKET>\fR
Path to Unix socket
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
start\-container\-action(1)
.TP
start\-container\-check\-dependencies(1)
.TP
start\-container\-echo(1)
.TP
start\-container\-get\-data\-version(1)
.TP
start\-container\-get\-dependencies(1)
.TP
start\-container\-get\-os\-ip(1)
.TP
start\-container\-get\-status(1)
.TP
start\-container\-git\-info(1)
.TP
start\-container\-plugin(1)
.TP
start\-container\-rebuild(1)
.TP
start\-container\-restart(1)
.TP
start\-container\-set\-data\-version(1)
.TP
start\-container\-set\-dependencies(1)
.TP
start\-container\-set\-main\-status(1)
.TP
start\-container\-shutdown(1)
.TP
start\-container\-subcontainer(1)
.SH VERSION
v0.4.0\-alpha.21
