.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-container-subcontainer-launch-init 1  "launch-init " 
.SH NAME
start\-container\-subcontainer\-launch\-init
.SH SYNOPSIS
\fBstart\-container subcontainer launch\-init\fR [\fB\-\-force\-tty\fR] [\fB\-\-force\-stderr\-tty\fR] [\fB\-\-pty\-size\fR] [\fB\-e\fR|\fB\-\-env\fR] [\fB\-\-env\-file\fR] [\fB\-w\fR|\fB\-\-workdir\fR] [\fB\-u\fR|\fB\-\-user\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fICHROOT\fR> [\fICOMMAND\fR] 
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-\-force\-tty\fR
Force TTY mode for I/O
.TP
\fB\-\-force\-stderr\-tty\fR
Force stderr to be treated as a TTY
.TP
\fB\-\-pty\-size\fR \fI<PTY_SIZE>\fR
PTY terminal size (<rows>:<cols>[:<x>:<y>])
.TP
\fB\-e\fR, \fB\-\-env\fR \fI<ENV>\fR
Environment variable (KEY=VALUE)
.TP
\fB\-\-env\-file\fR \fI<ENV_FILE>\fR
Path to environment file
.TP
\fB\-w\fR, \fB\-\-workdir\fR \fI<WORKDIR>\fR
Working directory path
.TP
\fB\-u\fR, \fB\-\-user\fR \fI<USER>\fR
User name to run as
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fICHROOT\fR>
Path for chroot environment
.TP
[\fICOMMAND\fR]
Command to execute in the container
