.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-container-action 1  "action " 
.SH NAME
start\-container\-action
.SH SYNOPSIS
\fBstart\-container action\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-container\-action\-clear(1)
.TP
start\-container\-action\-clear\-tasks(1)
.TP
start\-container\-action\-get\-input(1)
.TP
start\-container\-action\-run(1)
