// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WgSubnetConfig } from './WgSubnetConfig'

export type WgSubnetMap = { [key: string]: WgSubnetConfig }
