// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AddDnsRecordParams = {
  name: string
  type: string
  value: string
  ttl: number | null
}
