// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AddPortForwardParams = {
  /**
   * External (WAN) port to forward. The external IP is fixed to the target
   * device's assigned WAN: a forward's inbound IP must equal the device's
   * egress WAN so return traffic is symmetric.
   */
  externalPort: number
  target: string
  label: string | null
  /**
   * Hostnames to SNI-demux on the shared external port. Empty = normal DNAT.
   */
  sni: Array<string>
}
