// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which upstream a subnet's DNS proxy forwards to. Companion fields on
 * [`SetSubnetDnsParams`] supply the data for the `Device`/`Custom` modes.
 */
export type DnsMode = 'default' | 'device' | 'custom'
