// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A DNS record served by the tunnel — either injected by a device via RFC 2136
 * or added manually. `value` is the rdata rendered as text (an IP for A/AAAA,
 * a name for CNAME, the string for TXT).
 */
export type DnsRecordEntry = {
  name: string
  type: string
  value: string
  ttl: number
  /**
   * The device IP that injected this, or `null` for a manual record.
   */
  source: string | null
}
