// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SniRoute } from './SniRoute'

/**
 * One external-port forward: an nftables DNAT or an SNI-demultiplexed shared
 * port. Mutually exclusive for a given external address.
 */
export type PortForward =
  | {
      kind: 'dnat'
      target: string
      label: string | null
      enabled: boolean
      /**
       * Contiguous ports forwarded (a PCP PORT_SET range); `1` for single-port.
       */
      count: number
    }
  | {
      kind: 'sni'
      /**
       * hostname (lowercase; may be `*.suffix`) -> route.
       */
      routes: { [key: string]: SniRoute }
    }
