// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortForwardEntry } from './PortForwardEntry'

export type PortForwards = { [key: string]: PortForwardEntry }
