// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RemovePortForwardParams = {
  source: string
  /**
   * Remove a single SNI route on `source`; omit to remove the whole forward.
   */
  hostname: string | null
}
