// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DnsMode } from './DnsMode'

export type SetSubnetDnsParams = {
  mode: DnsMode
  /**
   * The selected device's WireGuard IP; required when `mode` is `device`.
   */
  deviceIp: string | null
  /**
   * Up to 3 upstream servers (bare IP or `ip:port`); used when `mode` is `custom`.
   */
  servers: string[]
}
