// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One SNI-demultiplexed hostname route on a shared external port.
 */
export type SniRoute = {
  target: string
  label: string | null
  enabled: boolean
}
