// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TunnelUpdateResult = {
  /**
   * "up-to-date", "update-available", or "updating"
   */
  status: string
  /**
   * Currently installed version
   */
  installed: string
  /**
   * Available candidate version
   */
  candidate: string
}
