// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnyVerifyingKey } from './AnyVerifyingKey'
import type { PortForwards } from './PortForwards'
import type { Sessions } from './Sessions'
import type { SignerInfo } from './SignerInfo'
import type { WebserverInfo } from './WebserverInfo'
import type { WgServer } from './WgServer'

export type TunnelDatabase = {
  webserver: WebserverInfo
  sessions: Sessions
  password: string | null
  authPubkeys: { [key: AnyVerifyingKey]: SignerInfo }
  gateways: { [key: AnyVerifyingKey]: SignerInfo }
  wg: WgServer
  portForwards: PortForwards
}
