// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TunnelCertData } from './TunnelCertData'

export type WebserverInfo = {
  enabled: boolean
  listen: string | null
  certificate: TunnelCertData | null
}
