// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Base64 } from "./Base64"
import type { WgSubnetMap } from "./WgSubnetMap"

export type WgServer = { port: number; key: Base64; subnets: WgSubnetMap }
