// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DnsConfig } from './DnsConfig'
import type { WgSubnetClients } from './WgSubnetClients'

export type WgSubnetConfig = {
  name: string
  clients: WgSubnetClients
  dns: DnsConfig
  /**
   * SNAT this subnet's egress to this WAN IP instead of `masquerade`. `None`
   * keeps the default masquerade; a per-device `wan_ip` overrides this.
   */
  wanIp: string | null
}
