.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-server-host-address-domain-public-remove 1  "remove " 
.SH NAME
start\-cli\-server\-host\-address\-domain\-public\-remove \- Remove public domain from host
.SH SYNOPSIS
\fBstart\-cli server host address domain public remove\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIFQDN\fR> 
.SH DESCRIPTION
Remove public domain from host
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFQDN\fR>
Fully qualified domain name
