.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-package-rebuild 1  "rebuild " 
.SH NAME
start\-cli\-package\-rebuild \- Rebuild service container
.SH SYNOPSIS
\fBstart\-cli package rebuild\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR> 
.SH DESCRIPTION
Rebuild service container
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>
Package identifier
