.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-setup-complete 1  "complete " 
.SH NAME
start\-cli\-setup\-complete \- Finalize the setup and persist disk identifiers
.SH SYNOPSIS
\fBstart\-cli setup complete\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Finalize the setup and persist disk identifiers
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
