.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-wifi-available 1  "available " 
.SH NAME
start\-cli\-wifi\-available \- Command to list available wifi networks
.SH SYNOPSIS
\fBstart\-cli wifi available\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Command to list available wifi networks
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-cli\-wifi\-available\-get(1)
List available wifi networks
