.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-setup-status 1  "status " 
.SH NAME
start\-cli\-setup\-status \- Display the current state of the setup wizard
.SH SYNOPSIS
\fBstart\-cli setup status\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Display the current state of the setup wizard
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
