.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-state 1  "state " 
.SH NAME
start\-cli\-state \- Display the current api specification
.SH SYNOPSIS
\fBstart\-cli state\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Display the current api specification
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
