.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-package-stop 1  "stop " 
.SH NAME
start\-cli\-package\-stop \- Stop a service
.SH SYNOPSIS
\fBstart\-cli package stop\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR> 
.SH DESCRIPTION
Stop a service
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>
Package identifier
