.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-kiosk 1  "kiosk " 
.SH NAME
start\-cli\-kiosk \- Commands for kiosk mode
.SH SYNOPSIS
\fBstart\-cli kiosk\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Commands for kiosk mode
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-cli\-kiosk\-disable(1)
Disable kiosk mode
.TP
start\-cli\-kiosk\-enable(1)
Enable kiosk mode
