.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-package-action 1  "action " 
.SH NAME
start\-cli\-package\-action \- Commands to get action input or run an action
.SH SYNOPSIS
\fBstart\-cli package action\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Commands to get action input or run an action
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-cli\-package\-action\-clear\-task(1)
Clear a service task
.TP
start\-cli\-package\-action\-get\-input(1)
Get action input specification
.TP
start\-cli\-package\-action\-run(1)
Run a service action
