.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-net-ssl 1  "ssl " 
.SH NAME
start\-cli\-net\-ssl \- Manage SSL certificates
.SH SYNOPSIS
\fBstart\-cli net ssl\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Manage SSL certificates
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-cli\-net\-ssl\-generate\-certificate(1)
Generate an SSL certificate from the system root CA
