.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-notification-create 1  "create " 
.SH NAME
start\-cli\-notification\-create \- Persist a new notification
.SH SYNOPSIS
\fBstart\-cli notification create\fR [\fB\-p\fR|\fB\-\-package\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fILEVEL\fR> <\fITITLE\fR> <\fIMESSAGE\fR> 
.SH DESCRIPTION
Persist a new notification
.SH OPTIONS
.TP
\fB\-p\fR, \fB\-\-package\fR \fI<PACKAGE>\fR
Package identifier
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fILEVEL\fR>
Notification severity level
.TP
<\fITITLE\fR>
Notification title
.TP
<\fIMESSAGE\fR>
Notification message content
