.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-server-experimental-zram 1  "zram " 
.SH NAME
start\-cli\-server\-experimental\-zram \- Enable ZRAM
.SH SYNOPSIS
\fBstart\-cli server experimental zram\fR [\fB\-\-enable\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Enable ZRAM
.SH OPTIONS
.TP
\fB\-\-enable\fR
Enable zram
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
