.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-setup-disk-list 1  "list " 
.SH NAME
start\-cli\-setup\-disk\-list \- List disks available for installation
.SH SYNOPSIS
\fBstart\-cli setup disk list\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List disks available for installation
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
