.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-package-host-binding 1  "binding " 
.SH NAME
start\-cli\-package\-host\-binding
.SH SYNOPSIS
\fBstart\-cli package host binding\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIHOST\fR> <\fIsubcommands\fR>
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIHOST\fR>
Host identifier
.SH SUBCOMMANDS
.TP
start\-cli\-package\-host\-binding\-list(1)
List bindings for a host
.TP
start\-cli\-package\-host\-binding\-set\-address\-enabled(1)
about.set\-address\-enabled\-for\-binding
