.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-setup-disk 1  "disk " 
.SH NAME
start\-cli\-setup\-disk
.SH SYNOPSIS
\fBstart\-cli setup disk\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-cli\-setup\-disk\-list(1)
List disks available for installation
