.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-setup-restart 1  "restart " 
.SH NAME
start\-cli\-setup\-restart \- about.setup\-restart
.SH SYNOPSIS
\fBstart\-cli setup restart\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
about.setup\-restart
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
