.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-setup 1  "setup " 
.SH NAME
start\-cli\-setup \- Commands related to the initial setup
.SH SYNOPSIS
\fBstart\-cli setup\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Commands related to the initial setup
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-cli\-setup\-attach(1)
about.setup\-attach
.TP
start\-cli\-setup\-cifs(1)
.TP
start\-cli\-setup\-complete(1)
about.setup\-complete
.TP
start\-cli\-setup\-disk(1)
.TP
start\-cli\-setup\-execute(1)
about.setup\-execute
.TP
start\-cli\-setup\-exit(1)
about.setup\-exit
.TP
start\-cli\-setup\-get\-pubkey(1)
about.setup\-get\-pubkey
.TP
start\-cli\-setup\-install\-os(1)
about.setup\-install\-os
.TP
start\-cli\-setup\-logs(1)
Display OS logs
.TP
start\-cli\-setup\-restart(1)
about.setup\-restart
.TP
start\-cli\-setup\-set\-keyboard(1)
about.setup\-set\-keyboard
.TP
start\-cli\-setup\-set\-language(1)
about.setup\-set\-language
.TP
start\-cli\-setup\-shutdown(1)
about.setup\-shutdown
.TP
start\-cli\-setup\-status(1)
about.setup\-status
