.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-net-acme-init 1  "init " 
.SH NAME
start\-cli\-net\-acme\-init \- Setup ACME certificate acquisition
.SH SYNOPSIS
\fBstart\-cli net acme init\fR <\fB\-\-provider\fR> [\fB\-\-contact\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Setup ACME certificate acquisition
.SH OPTIONS
.TP
\fB\-\-provider\fR \fI<PROVIDER>\fR
ACME provider identifier or url
.TP
\fB\-\-contact\fR \fI<CONTACT>\fR
Contact email for ACME certificate authority
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
