.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-registry-os-version-signer 1  "signer " 
.SH NAME
start\-cli\-registry\-os\-version\-signer \- Add, remove, and list version signers
.SH SYNOPSIS
\fBstart\-cli registry os version signer\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Add, remove, and list version signers
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-cli\-registry\-os\-version\-signer\-add(1)
Add version signer
.TP
start\-cli\-registry\-os\-version\-signer\-list(1)
List version signers
.TP
start\-cli\-registry\-os\-version\-signer\-remove(1)
Remove version signer
