.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-wifi 1  "wifi " 
.SH NAME
start\-cli\-wifi \- Commands related to wifi networks i.e. add, connect, delete
.SH SYNOPSIS
\fBstart\-cli wifi\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Commands related to wifi networks i.e. add, connect, delete
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-cli\-wifi\-add(1)
Add wifi ssid and password
.TP
start\-cli\-wifi\-available(1)
Command to list available wifi networks
.TP
start\-cli\-wifi\-connect(1)
Connect to a wifi network
.TP
start\-cli\-wifi\-country(1)
Command to set country
.TP
start\-cli\-wifi\-get(1)
List wifi information
.TP
start\-cli\-wifi\-remove(1)
Remove a wifi network
.TP
start\-cli\-wifi\-set\-enabled(1)
Enable or disable wifi
