.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-net-tunnel-remove 1  "remove " 
.SH NAME
start\-cli\-net\-tunnel\-remove \- Remove a tunnel
.SH SYNOPSIS
\fBstart\-cli net tunnel remove\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR> 
.SH DESCRIPTION
Remove a tunnel
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>
Gateway identifier
