.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-wifi-country 1  "country " 
.SH NAME
start\-cli\-wifi\-country \- Command to set country
.SH SYNOPSIS
\fBstart\-cli wifi country\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Command to set country
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-cli\-wifi\-country\-set(1)
Set the country
