.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-net-gateway-forget 1  "forget " 
.SH NAME
start\-cli\-net\-gateway\-forget \- Forget a disconnected gateway
.SH SYNOPSIS
\fBstart\-cli net gateway forget\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIGATEWAY\fR> 
.SH DESCRIPTION
Forget a disconnected gateway
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIGATEWAY\fR>
Gateway identifier
