.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-registry-info 1  "info " 
.SH NAME
start\-cli\-registry\-info \- Display registry info
.SH SYNOPSIS
\fBstart\-cli registry info\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIsubcommands\fR]
.SH DESCRIPTION
Display registry info
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-cli\-registry\-info\-set\-icon(1)
Set the registry icon
.TP
start\-cli\-registry\-info\-set\-name(1)
Set the registry name
