.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-registry-metrics-summary 1  "summary " 
.SH NAME
start\-cli\-registry\-metrics\-summary \- Get a summary of registry usage metrics
.SH SYNOPSIS
\fBstart\-cli registry metrics summary\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Get a summary of registry usage metrics
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
