.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-package-installed-version 1  "installed-version " 
.SH NAME
start\-cli\-package\-installed\-version \- Display the installed version of a package
.SH SYNOPSIS
\fBstart\-cli package installed\-version\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR> 
.SH DESCRIPTION
Display the installed version of a package
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>
Package identifier
