.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-registry-os-asset-get-iso 1  "iso " 
.SH NAME
start\-cli\-registry\-os\-asset\-get\-iso \- Download ISO file
.SH SYNOPSIS
\fBstart\-cli registry os asset get iso\fR [\fB\-d\fR|\fB\-\-download\fR] [\fB\-r\fR|\fB\-\-reverify\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIVERSION\fR> <\fIPLATFORM\fR> 
.SH DESCRIPTION
Download ISO file
.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-download\fR \fI<DOWNLOAD>\fR [default: .]
Directory path to download to
.TP
\fB\-r\fR, \fB\-\-reverify\fR
Verify hash after download completes
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIVERSION\fR>
StartOS version number
.TP
<\fIPLATFORM\fR>
Target platform identifier
