.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-server-host-address-list 1  "list " 
.SH NAME
start\-cli\-server\-host\-address\-list \- List addresses for a host
.SH SYNOPSIS
\fBstart\-cli server host address list\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List addresses for a host
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
