.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-package-set-outbound-gateway 1  "set-outbound-gateway " 
.SH NAME
start\-cli\-package\-set\-outbound\-gateway \- Set the outbound gateway for a package
.SH SYNOPSIS
\fBstart\-cli package set\-outbound\-gateway\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIPACKAGE\fR> [\fIGATEWAY\fR] 
.SH DESCRIPTION
Set the outbound gateway for a package
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPACKAGE\fR>
Package identifier
.TP
[\fIGATEWAY\fR]
Gateway identifier
