.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-registry-info-set-icon 1  "set-icon " 
.SH NAME
start\-cli\-registry\-info\-set\-icon \- Set the registry icon
.SH SYNOPSIS
\fBstart\-cli registry info set\-icon\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIICON\fR> 
.SH DESCRIPTION
Set the registry icon
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIICON\fR>
Path to service icon file
