.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-tunnel-web-uninit 1  "uninit " 
.SH NAME
start\-cli\-tunnel\-web\-uninit \- Uninitialize the webserver
.SH SYNOPSIS
\fBstart\-cli tunnel web uninit\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Uninitialize the webserver
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
