.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-registry-db-dump 1  "dump " 
.SH NAME
start\-cli\-registry\-db\-dump \- Filter and query the database
.SH SYNOPSIS
\fBstart\-cli registry db dump\fR [\fB\-p\fR|\fB\-\-pointer\fR] [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIPATH\fR] 
.SH DESCRIPTION
Filter and query the database
.SH OPTIONS
.TP
\fB\-p\fR, \fB\-\-pointer\fR \fI<POINTER>\fR
JSON pointer to object in database to dump
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIPATH\fR]
Path to the database file
