.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-package-action-run 1  "run " 
.SH NAME
start\-cli\-package\-action\-run \- Run a service action
.SH SYNOPSIS
\fBstart\-cli package action run\fR [\fB\-\-event\-id\fR] [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIPACKAGE_ID\fR> <\fIACTION_ID\fR> 
.SH DESCRIPTION
Run a service action
.SH OPTIONS
.TP
\fB\-\-event\-id\fR \fI<EVENT_ID>\fR
Unique event identifier
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPACKAGE_ID\fR>
Package identifier
.TP
<\fIACTION_ID\fR>
Action identifier
