.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-net-dns-set-static 1  "set-static " 
.SH NAME
start\-cli\-net\-dns\-set\-static \- Set static DNS servers
.SH SYNOPSIS
\fBstart\-cli net dns set\-static\fR [\fB\-h\fR|\fB\-\-help\fR] [\fISERVERS\fR] 
.SH DESCRIPTION
Set static DNS servers
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fISERVERS\fR]
DNS servers to use
