.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-tunnel 1  "tunnel " 
.SH NAME
start\-cli\-tunnel \- Commands related to StartTunnel
.SH SYNOPSIS
\fBstart\-cli tunnel\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Commands related to StartTunnel
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-cli\-tunnel\-auth(1)
Add or remove authorized clients
.TP
start\-cli\-tunnel\-db(1)
Commands to interact with the db i.e. dump and apply
.TP
start\-cli\-tunnel\-device(1)
Add, remove, or list devices in subnets
.TP
start\-cli\-tunnel\-port\-forward(1)
Commands for managing port forwards
.TP
start\-cli\-tunnel\-restart(1)
Reboot the tunnel server
.TP
start\-cli\-tunnel\-subnet(1)
Add, remove, or modify subnets
.TP
start\-cli\-tunnel\-update(1)
Commands for checking and applying tunnel updates
.TP
start\-cli\-tunnel\-web(1)
Commands for managing the tunnel web interface
