.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-tunnel-web 1  "web " 
.SH NAME
start\-cli\-tunnel\-web \- Commands for managing the tunnel web interface
.SH SYNOPSIS
\fBstart\-cli tunnel web\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Commands for managing the tunnel web interface
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-cli\-tunnel\-web\-disable(1)
Disable the webserver
.TP
start\-cli\-tunnel\-web\-enable(1)
Enable the webserver
.TP
start\-cli\-tunnel\-web\-generate\-certificate(1)
Generate a certificate for the webserver
.TP
start\-cli\-tunnel\-web\-get\-available\-ips(1)
Get available IP addresses to bind
.TP
start\-cli\-tunnel\-web\-get\-certificate(1)
Get the certificate for the webserver
.TP
start\-cli\-tunnel\-web\-get\-listen(1)
Get the listen address for the webserver
.TP
start\-cli\-tunnel\-web\-import\-certificate(1)
Import a certificate for the webserver
.TP
start\-cli\-tunnel\-web\-init(1)
Initialize the webserver
.TP
start\-cli\-tunnel\-web\-set\-listen(1)
Set the listen address for the webserver
.TP
start\-cli\-tunnel\-web\-uninit(1)
Uninitialize the webserver
