.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-ssh-remove 1  "remove " 
.SH NAME
start\-cli\-ssh\-remove \- Remove an SSH key
.SH SYNOPSIS
\fBstart\-cli ssh remove\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIFINGERPRINT\fR> 
.SH DESCRIPTION
Remove an SSH key
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFINGERPRINT\fR>
SSH key fingerprint
