.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-registry-os-version-signer-remove 1  "remove " 
.SH NAME
start\-cli\-registry\-os\-version\-signer\-remove \- Remove version signer
.SH SYNOPSIS
\fBstart\-cli registry os version signer remove\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIVERSION\fR> <\fISIGNER\fR> 
.SH DESCRIPTION
Remove version signer
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIVERSION\fR>

.TP
<\fISIGNER\fR>

