.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-server-experimental 1  "experimental " 
.SH NAME
start\-cli\-server\-experimental \- Commands related to configuring experimental options such as zram and cpu governor
.SH SYNOPSIS
\fBstart\-cli server experimental\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Commands related to configuring experimental options such as zram and cpu governor
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-cli\-server\-experimental\-governor(1)
Show CPU governors
.TP
start\-cli\-server\-experimental\-zram(1)
Enable ZRAM
