.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-wifi-available-get 1  "get " 
.SH NAME
start\-cli\-wifi\-available\-get \- List available wifi networks
.SH SYNOPSIS
\fBstart\-cli wifi available get\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List available wifi networks
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
