.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-tunnel-web-get-listen 1  "get-listen " 
.SH NAME
start\-cli\-tunnel\-web\-get\-listen \- Get the listen address for the webserver
.SH SYNOPSIS
\fBstart\-cli tunnel web get\-listen\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Get the listen address for the webserver
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
