.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-tunnel-port-forward-set-enabled 1  "set-enabled " 
.SH NAME
start\-cli\-tunnel\-port\-forward\-set\-enabled \- about.enable\-or\-disable\-port\-forward
.SH SYNOPSIS
\fBstart\-cli tunnel port\-forward set\-enabled\fR [\fB\-\-enabled\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fISOURCE\fR> 
.SH DESCRIPTION
about.enable\-or\-disable\-port\-forward
.SH OPTIONS
.TP
\fB\-\-enabled\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISOURCE\fR>

