.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-net-vhost-add-passthrough 1  "add-passthrough " 
.SH NAME
start\-cli\-net\-vhost\-add\-passthrough
.SH SYNOPSIS
\fBstart\-cli net vhost add\-passthrough\fR <\fB\-\-hostname\fR> <\fB\-\-listen\-port\fR> <\fB\-\-backend\fR> [\fB\-\-public\-gateway\fR] [\fB\-\-private\-ip\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-\-hostname\fR \fI<HOSTNAME>\fR

.TP
\fB\-\-listen\-port\fR \fI<LISTEN_PORT>\fR

.TP
\fB\-\-backend\fR \fI<BACKEND>\fR

.TP
\fB\-\-public\-gateway\fR \fI<PUBLIC_GATEWAY>\fR

.TP
\fB\-\-private\-ip\fR \fI<PRIVATE_IP>\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
