.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-package-cancel-install 1  "cancel-install " 
.SH NAME
start\-cli\-package\-cancel\-install \- Cancel an install of a package
.SH SYNOPSIS
\fBstart\-cli package cancel\-install\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR> 
.SH DESCRIPTION
Cancel an install of a package
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>
Package identifier
