.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-net-ssl-generate-certificate 1  "generate-certificate " 
.SH NAME
start\-cli\-net\-ssl\-generate\-certificate \- Generate an SSL certificate from the system root CA
.SH SYNOPSIS
\fBstart\-cli net ssl generate\-certificate\fR [\fB\-\-ed25519\fR] [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIHOSTNAMES\fR] 
.SH DESCRIPTION
Generate an SSL certificate from the system root CA
.SH OPTIONS
.TP
\fB\-\-ed25519\fR
Use Ed25519 instead of NIST P\-256
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIHOSTNAMES\fR]
Hostnames to include in the certificate
