.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-package-action-clear-task 1  "clear-task " 
.SH NAME
start\-cli\-package\-action\-clear\-task \- Clear a service task
.SH SYNOPSIS
\fBstart\-cli package action clear\-task\fR [\fB\-\-force\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIPACKAGE_ID\fR> <\fIREPLAY_ID\fR> 
.SH DESCRIPTION
Clear a service task
.SH OPTIONS
.TP
\fB\-\-force\fR
Force clear the task even if running
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPACKAGE_ID\fR>
Package identifier
.TP
<\fIREPLAY_ID\fR>
Replay identifier for task
