.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-net-acme 1  "acme " 
.SH NAME
start\-cli\-net\-acme \- Setup ACME certificate
.SH SYNOPSIS
\fBstart\-cli net acme\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Setup ACME certificate
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-cli\-net\-acme\-init(1)
Setup ACME certificate acquisition
.TP
start\-cli\-net\-acme\-remove(1)
Remove ACME certificate acquisition configuration
