.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-registry-index 1  "index " 
.SH NAME
start\-cli\-registry\-index \- List registry info and packages
.SH SYNOPSIS
\fBstart\-cli registry index\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List registry info and packages
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
