.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-wifi-remove 1  "remove " 
.SH NAME
start\-cli\-wifi\-remove \- Remove a wifi network
.SH SYNOPSIS
\fBstart\-cli wifi remove\fR [\fB\-h\fR|\fB\-\-help\fR] <\fISSID\fR> 
.SH DESCRIPTION
Remove a wifi network
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISSID\fR>
WiFi network SSID
