.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-setup-exit 1  "exit " 
.SH NAME
start\-cli\-setup\-exit \- Exit setup mode and reboot into the installed OS
.SH SYNOPSIS
\fBstart\-cli setup exit\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Exit setup mode and reboot into the installed OS
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
