.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-setup-execute 1  "execute " 
.SH NAME
start\-cli\-setup\-execute \- about.setup\-execute
.SH SYNOPSIS
\fBstart\-cli setup execute\fR <\fB\-\-guid\fR> [\fB\-\-kiosk\fR] [\fB\-\-name\fR] [\fB\-\-hostname\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
about.setup\-execute
.SH OPTIONS
.TP
\fB\-\-guid\fR \fI<GUID>\fR
Disk GUID returned by `setup install\-os` (or an existing data drive)
.TP
\fB\-\-kiosk\fR
Enable kiosk mode
.TP
\fB\-\-name\fR \fI<NAME>\fR
Friendly server name
.TP
\fB\-\-hostname\fR \fI<HOSTNAME>\fR
Hostname (LAN advertised) — defaults to a random adjective\-noun pair
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
