.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-server-device-info 1  "device-info " 
.SH NAME
start\-cli\-server\-device\-info \- about.get\-device\-info
.SH SYNOPSIS
\fBstart\-cli server device\-info\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
about.get\-device\-info
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
