.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-server-host-address-domain-private 1  "private " 
.SH NAME
start\-cli\-server\-host\-address\-domain\-private
.SH SYNOPSIS
\fBstart\-cli server host address domain private\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-cli\-server\-host\-address\-domain\-private\-add(1)
Add a private domain to this host
.TP
start\-cli\-server\-host\-address\-domain\-private\-remove(1)
Remove private domain from host
