.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-server-experimental-governor 1  "governor " 
.SH NAME
start\-cli\-server\-experimental\-governor \- Show CPU governors
.SH SYNOPSIS
\fBstart\-cli server experimental governor\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fISET\fR] 
.SH DESCRIPTION
Show CPU governors
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fISET\fR]
CPU governor name
