.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-package-stats 1  "stats " 
.SH NAME
start\-cli\-package\-stats \- List LXC container information
.SH SYNOPSIS
\fBstart\-cli package stats\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List LXC container information
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
