.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-registry-package-remove 1  "remove " 
.SH NAME
start\-cli\-registry\-package\-remove \- Remove package from registry
.SH SYNOPSIS
\fBstart\-cli registry package remove\fR [\fB\-\-sighash\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR> <\fIVERSION\fR> 
.SH DESCRIPTION
Remove package from registry
.SH OPTIONS
.TP
\fB\-\-sighash\fR \fI<SIGHASH>\fR
Hash for signature verification
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>
Package identifier
.TP
<\fIVERSION\fR>
Package version
