.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-s9pk-publish 1  "publish " 
.SH NAME
start\-cli\-s9pk\-publish \- Publish s9pk to S3 bucket and index on registry
.SH SYNOPSIS
\fBstart\-cli s9pk publish\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIS9PK\fR> 
.SH DESCRIPTION
Publish s9pk to S3 bucket and index on registry
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIS9PK\fR>
Path to s9pk package file
