.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-package-backup-restore 1  "restore " 
.SH NAME
start\-cli\-package\-backup\-restore \- Restore packages from backup
.SH SYNOPSIS
\fBstart\-cli package backup restore\fR [\fB\-h\fR|\fB\-\-help\fR] <\fITARGET_ID\fR> <\fIPASSWORD\fR> [\fIIDS\fR] 
.SH DESCRIPTION
Restore packages from backup
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fITARGET_ID\fR>
Backup target identifier
.TP
<\fIPASSWORD\fR>
Password for backup encryption
.TP
[\fIIDS\fR]
Package identifiers
