.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-tunnel-restart 1  "restart " 
.SH NAME
start\-cli\-tunnel\-restart \- Reboot the tunnel server
.SH SYNOPSIS
\fBstart\-cli tunnel restart\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Reboot the tunnel server
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
