.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-net-gateway-check-dns 1  "check-dns " 
.SH NAME
start\-cli\-net\-gateway\-check\-dns \- Check DNS configuration for a gateway
.SH SYNOPSIS
\fBstart\-cli net gateway check\-dns\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIGATEWAY\fR> 
.SH DESCRIPTION
Check DNS configuration for a gateway
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIGATEWAY\fR>
Gateway identifier
