.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-server-metrics 1  "metrics " 
.SH NAME
start\-cli\-server\-metrics \- Display server metrics
.SH SYNOPSIS
\fBstart\-cli server metrics\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Display server metrics
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
