.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-tunnel-port-forward 1  "port-forward " 
.SH NAME
start\-cli\-tunnel\-port\-forward
.SH SYNOPSIS
\fBstart\-cli tunnel port\-forward\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-cli\-tunnel\-port\-forward\-add(1)
Add a new port forward
.TP
start\-cli\-tunnel\-port\-forward\-remove(1)
Remove port forward
.TP
start\-cli\-tunnel\-port\-forward\-set\-enabled(1)
about.enable\-or\-disable\-port\-forward
.TP
start\-cli\-tunnel\-port\-forward\-update\-label(1)
about.update\-port\-forward\-label
