.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-s9pk-inspect-commitment 1  "commitment " 
.SH NAME
start\-cli\-s9pk\-inspect\-commitment \- about.display\-s9pk\-root\-sighash\-and\-maxsize
.SH SYNOPSIS
\fBstart\-cli s9pk inspect commitment\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
about.display\-s9pk\-root\-sighash\-and\-maxsize
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
