.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-package-attach 1  "attach " 
.SH NAME
start\-cli\-package\-attach
.SH SYNOPSIS
\fBstart\-cli package attach\fR [\fB\-\-force\-tty\fR] [\fB\-s\fR|\fB\-\-subcontainer\fR] [\fB\-n\fR|\fB\-\-name\fR] [\fB\-u\fR|\fB\-\-user\fR] [\fB\-i\fR|\fB\-\-image\-id\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR> [\fICOMMAND\fR] 
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-\-force\-tty\fR
Force TTY mode for I/O
.TP
\fB\-s\fR, \fB\-\-subcontainer\fR \fI<SUBCONTAINER>\fR
Name of the subcontainer
.TP
\fB\-n\fR, \fB\-\-name\fR \fI<NAME>\fR
Name of the container
.TP
\fB\-u\fR, \fB\-\-user\fR \fI<USER>\fR
User name to run as
.TP
\fB\-i\fR, \fB\-\-image\-id\fR \fI<IMAGE_ID>\fR
Docker image identifier
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>
Package identifier
.TP
[\fICOMMAND\fR]
Command to execute in the container
