.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-registry-admin-remove 1  "remove " 
.SH NAME
start\-cli\-registry\-admin\-remove \- Remove admin signer
.SH SYNOPSIS
\fBstart\-cli registry admin remove\fR [\fB\-h\fR|\fB\-\-help\fR] <\fISIGNER\fR> 
.SH DESCRIPTION
Remove admin signer
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISIGNER\fR>
Signer identifier
