.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-wifi-get 1  "get " 
.SH NAME
start\-cli\-wifi\-get \- List wifi information
.SH SYNOPSIS
\fBstart\-cli wifi get\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List wifi information
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
