.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-setup-get-pubkey 1  "get-pubkey " 
.SH NAME
start\-cli\-setup\-get\-pubkey \- about.setup\-get\-pubkey
.SH SYNOPSIS
\fBstart\-cli setup get\-pubkey\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
about.setup\-get\-pubkey
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
