.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-setup 1  "setup " 
.SH NAME
start\-cli\-setup \- Commands related to the initial setup
.SH SYNOPSIS
\fBstart\-cli setup\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Commands related to the initial setup
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-cli\-setup\-cifs(1)
.TP
start\-cli\-setup\-disk(1)
.TP
start\-cli\-setup\-logs(1)
Display OS logs
