// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WgConfig } from './WgConfig'

export type WgSubnetClients = { [key: string]: WgConfig }
