use crate::profiles::UciProfile;
use crate::CtrlContext;
use crate::Error;
use serde::{Deserialize, Serialize};
use uciedit::Configs;

/// A single DNS server entry with protocol info.
/// `ssl: false` = plain UDP on port 53.
/// `ssl: true`  = DNS-over-HTTPS via SmartDNS (`server-https`).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct DnsServer {
    pub address: String, // always an IPv4 address
    pub ssl: bool,
}

/// SmartDNS bind port constants.
pub const SMARTDNS_SYSTEM_PORT: u16 = 5300;
pub const SMARTDNS_CONF_PATH: &str = "/etc/smartdns/smartdns.conf";

/// Compute the SmartDNS port for a profile's VLAN tag.
pub fn smartdns_port_for_vlan(vlan_tag: u16) -> u16 {
    SMARTDNS_SYSTEM_PORT + vlan_tag
}

/// A SmartDNS server group with its bind address and upstream servers.
pub struct SmartDnsGroup {
    pub name: String,
    pub port: u16,
    pub servers: Vec<DnsServer>,
}

/// Generate the full `smartdns.conf` content from a list of groups.
pub fn generate_smartdns_conf(groups: &[SmartDnsGroup]) -> String {
    let mut conf = String::from("# Auto-generated by StartWRT. Do not edit.\nserver-name startwrt-smartdns\nlog-level warn\n");

    for group in groups {
        conf.push('\n');
        conf.push_str(&format!(
            "bind 127.0.0.1:{} -group {} -no-rule-addr -no-rule-nameserver -no-rule-ipset -no-rule-soa -no-dualstack-selection\n",
            group.port, group.name
        ));
        for server in &group.servers {
            if server.ssl {
                conf.push_str(&format!(
                    "server-https https://{}/dns-query -group {} -exclude-default-group\n",
                    server.address, group.name
                ));
            } else {
                conf.push_str(&format!(
                    "server {} -group {} -exclude-default-group\n",
                    server.address, group.name
                ));
            }
        }
    }
    conf
}

/// Parse a list of JSON-encoded DnsServer entries from UCI.
pub fn parse_dns_server_list(entries: &[String]) -> Vec<DnsServer> {
    entries
        .iter()
        .filter_map(|s| serde_json::from_str(s).ok())
        .collect()
}

/// Serialize DnsServer entries to JSON strings for UCI storage.
pub fn serialize_dns_server_list(servers: &[DnsServer]) -> Vec<String> {
    servers
        .iter()
        .map(|s| serde_json::to_string(s).unwrap())
        .collect()
}

/// Read system DNS servers from the `system_dns` section in `/etc/config/startwrt`.
pub fn get_system_dns_servers(cfgs: &Configs) -> Vec<DnsServer> {
    use uciedit::openwrt::UciSystemDns;

    for section in &cfgs["startwrt"].sections {
        if let Ok(sys_dns) = section.get::<UciSystemDns>() {
            if section.name().as_deref() == Some("system_dns") {
                return parse_dns_server_list(&sys_dns.servers);
            }
        }
    }
    Vec::new()
}

/// Collect all SmartDNS groups (system + per-profile) from the current config.
pub fn collect_smartdns_groups(cfgs: &Configs) -> Vec<SmartDnsGroup> {
    let mut groups = Vec::new();

    // System DNS group
    let system_servers = get_system_dns_servers(cfgs);
    if !system_servers.is_empty() {
        groups.push(SmartDnsGroup {
            name: "system".into(),
            port: SMARTDNS_SYSTEM_PORT,
            servers: system_servers,
        });
    }

    // Per-profile DNS groups (only for profiles with custom dns_override)
    for section in &cfgs["startwrt"].sections {
        if let Ok(profile) = section.get::<UciProfile>() {
            let servers = parse_dns_server_list(&profile.dns_override);
            if !servers.is_empty() {
                groups.push(SmartDnsGroup {
                    name: format!("profile_{}", profile.interface),
                    port: smartdns_port_for_vlan(profile.vlan_tag),
                    servers,
                });
            }
        }
    }

    groups
}

/// Regenerate `/etc/smartdns/smartdns.conf` from current config state and restart SmartDNS.
pub fn regenerate_smartdns(ctx: &impl CtrlContext, cfgs: &Configs) -> Result<(), Error> {
    if !ctx.effectful() {
        return Ok(());
    }

    let groups = collect_smartdns_groups(cfgs);

    if groups.is_empty() {
        let _ = std::fs::write(SMARTDNS_CONF_PATH, "# No DNS groups configured\n");
        let _ = std::process::Command::new("/etc/init.d/smartdns")
            .arg("stop")
            .spawn()
            .and_then(|mut c| c.wait());
        return Ok(());
    }

    let conf = generate_smartdns_conf(&groups);
    std::fs::create_dir_all("/etc/smartdns")?;
    std::fs::write(SMARTDNS_CONF_PATH, &conf)?;
    let _ = std::process::Command::new("/etc/init.d/smartdns")
        .arg("restart")
        .spawn()
        .and_then(|mut c| c.wait());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_smartdns_port_for_vlan() {
        assert_eq!(smartdns_port_for_vlan(1), 5301);
        assert_eq!(smartdns_port_for_vlan(101), 5401);
        assert_eq!(smartdns_port_for_vlan(0), 5300);
    }

    #[test]
    fn test_generate_smartdns_conf_single_group_mixed() {
        let groups = vec![SmartDnsGroup {
            name: "system".into(),
            port: 5300,
            servers: vec![
                DnsServer {
                    address: "1.1.1.1".into(),
                    ssl: false,
                },
                DnsServer {
                    address: "8.8.8.8".into(),
                    ssl: true,
                },
            ],
        }];
        let conf = generate_smartdns_conf(&groups);
        assert!(conf.contains("bind 127.0.0.1:5300 -group system"));
        assert!(conf.contains("server 1.1.1.1 -group system -exclude-default-group"));
        assert!(conf.contains(
            "server-https https://8.8.8.8/dns-query -group system -exclude-default-group"
        ));
    }

    #[test]
    fn test_generate_smartdns_conf_multiple_groups() {
        let groups = vec![
            SmartDnsGroup {
                name: "system".into(),
                port: 5300,
                servers: vec![DnsServer {
                    address: "9.9.9.9".into(),
                    ssl: false,
                }],
            },
            SmartDnsGroup {
                name: "profile_guest".into(),
                port: 5401,
                servers: vec![
                    DnsServer {
                        address: "1.1.1.1".into(),
                        ssl: false,
                    },
                    DnsServer {
                        address: "8.8.8.8".into(),
                        ssl: true,
                    },
                ],
            },
        ];
        let conf = generate_smartdns_conf(&groups);
        assert!(conf.contains("bind 127.0.0.1:5300 -group system"));
        assert!(conf.contains("server 9.9.9.9 -group system"));
        assert!(conf.contains("bind 127.0.0.1:5401 -group profile_guest"));
        assert!(conf.contains("server 1.1.1.1 -group profile_guest"));
        assert!(conf.contains("server-https https://8.8.8.8/dns-query -group profile_guest"));
    }

    #[test]
    fn test_generate_smartdns_conf_empty() {
        let groups: Vec<SmartDnsGroup> = vec![];
        let conf = generate_smartdns_conf(&groups);
        assert!(conf.contains("Auto-generated"));
        assert!(!conf.contains("bind"));
    }

    #[test]
    fn test_parse_dns_server_list() {
        let entries = vec![
            r#"{"address":"1.1.1.1","ssl":false}"#.to_string(),
            r#"{"address":"8.8.8.8","ssl":true}"#.to_string(),
        ];
        let servers = parse_dns_server_list(&entries);
        assert_eq!(servers.len(), 2);
        assert_eq!(
            servers[0],
            DnsServer {
                address: "1.1.1.1".into(),
                ssl: false
            }
        );
        assert_eq!(
            servers[1],
            DnsServer {
                address: "8.8.8.8".into(),
                ssl: true
            }
        );
    }

    #[test]
    fn test_parse_dns_server_list_invalid() {
        let entries = vec![
            "not json".to_string(),
            r#"{"address":"1.1.1.1","ssl":false}"#.to_string(),
        ];
        let servers = parse_dns_server_list(&entries);
        assert_eq!(servers.len(), 1);
        assert_eq!(
            servers[0],
            DnsServer {
                address: "1.1.1.1".into(),
                ssl: false
            }
        );
    }

    #[test]
    fn test_serialize_round_trip() {
        let servers = vec![
            DnsServer {
                address: "1.1.1.1".into(),
                ssl: false,
            },
            DnsServer {
                address: "8.8.8.8".into(),
                ssl: true,
            },
        ];
        let serialized = serialize_dns_server_list(&servers);
        let parsed = parse_dns_server_list(&serialized);
        assert_eq!(servers, parsed);
    }

    #[test]
    fn test_smartdns_conf_output_exact() {
        let groups = vec![
            SmartDnsGroup {
                name: "system".into(),
                port: 5300,
                servers: vec![DnsServer {
                    address: "9.9.9.9".into(),
                    ssl: false,
                }],
            },
            SmartDnsGroup {
                name: "profile_guest".into(),
                port: 5401,
                servers: vec![
                    DnsServer {
                        address: "1.1.1.1".into(),
                        ssl: false,
                    },
                    DnsServer {
                        address: "8.8.8.8".into(),
                        ssl: true,
                    },
                ],
            },
        ];
        let conf = generate_smartdns_conf(&groups);
        let expected = "\
# Auto-generated by StartWRT. Do not edit.
server-name startwrt-smartdns
log-level warn

bind 127.0.0.1:5300 -group system -no-rule-addr -no-rule-nameserver -no-rule-ipset -no-rule-soa -no-dualstack-selection
server 9.9.9.9 -group system -exclude-default-group

bind 127.0.0.1:5401 -group profile_guest -no-rule-addr -no-rule-nameserver -no-rule-ipset -no-rule-soa -no-dualstack-selection
server 1.1.1.1 -group profile_guest -exclude-default-group
server-https https://8.8.8.8/dns-query -group profile_guest -exclude-default-group
";
        assert_eq!(conf, expected);
    }
}
