name: 🐛 Bug Report
description: Create a report to help us improve EmbassyOS
title: '[bug]: '
labels: ["Bug", "Needs Triage"]
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following.
      options:
        - label: I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already report this problem, without success.
          required: true
  - type: input
    attributes:
      label: EmbassyOS Version
      description: What version of EmbassyOS are you running? For EmbassyOS 0.2.x issues, please use https://github.com/start9labs/eos-0.2.x.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Device
      description: What device are you using to connect to Embassy?
      options:
        - Phone/tablet
        - Laptop/Desktop
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Operating System
      description: What operating system is your device running?
      options:
        - Linux
        - MacOS
        - Windows
        - iOS
        - Android
        - CalyxOS
        - GrapheneOS
        - Other
    validations:
      required: true
  - type: input
    attributes:
      label: OS Version
      description: What version is your operating system?
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Browser
      description: What browser are you using to connect to Embassy?
      options:
        - Tor Browser
        - Firefox
        - Brave
        - Safari
        - Chrome
        - Opera
        - Edge
        - Internet Explorer
        - Other
    validations:
      required: true
  - type: input
    attributes:
      label: Browser Version
      description: What version is your browser?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A clear description of what the bug is and how it manifests.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce this behavior.
      placeholder: |
        1. On this page...
        2. Click this button...
        3. Enter this value...
        4. See error...
    validations:
      required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Screenshots? Links? References? Anything that will give us more context about the issue you are encountering.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.