contact_links:
  - name: 📚 Documentation
    url: https://github.com/start9labs/documentation
    about: This issue tracker is not for documentation issues. Please file documentation issues on the Start9 Docs repo.
  - name: 🤔 Support Question
    url: https://t.me/start9_labs
    about: This issue tracker is not for support questions. Please post your question in our Telegram community channel.