name: 💡 Feature Request
description: Suggest an idea for EmbassyOS
title: '[feat]: '
labels: [Enhancement]
assignees:
  - MattDHill
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Please confirm you have completed the following.
      options:
        - label: I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature.
          required: true
  - type: textarea
    attributes:
      label: Describe the Feature Request
      description: A clear and concise description of the feature.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the Use Case
      description: Why is this feature useful? What problem does it solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe Preferred Solution
      description: How you want this feature added to EmbassyOS?
  - type: textarea
    attributes:
      label: Describe Alternatives
      description: Describe any alternative solutions or features you have considered.
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Screenshots? Links? References? Anything that will give us more context about the feature you are suggesting.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
