// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnyVerifyingKey } from "./AnyVerifyingKey"

export type AcceptSigners =
  | { signer: AnyVerifyingKey }
  | { any: Array<AcceptSigners> }
  | { all: Array<AcceptSigners> }
