// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AcmeSettings = {
  provider: string
  /**
   * email addresses for letsencrypt
   */
  contact: Array<string>
  /**
   * domains to get letsencrypt certs for
   */
  domains: string[]
}
