// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActionResultMember = {
  /**
   * A human-readable name or title of the value, such as "Last Active" or "Login Password"
   */
  name: string
  /**
   * (optional) A description of the value, such as an explaining why it exists or how to use it
   */
  description: string | null
} & (
  | {
      type: "single"
      /**
       * The actual string value to display
       */
      value: string
      /**
       * Whether or not to include a copy to clipboard icon to copy the value
       */
      copyable: boolean
      /**
       * Whether or not to also display the value as a QR code
       */
      qr: boolean
      /**
       * Whether or not to mask the value using ●●●●●●●, which is useful for password or other sensitive information
       */
      masked: boolean
    }
  | {
      type: "group"
      /**
       * An new group of nested values, experienced by the user as an accordion dropdown
       */
      value: Array<ActionResultMember>
    }
)
