// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionResultValue } from "./ActionResultValue"

export type ActionResultV1 = {
  title: string
  message: string | null
  result: ActionResultValue | null
}
