// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionResultV0 } from "./ActionResultV0"
import type { ActionResultV1 } from "./ActionResultV1"

export type ActionResult =
  | ({ version: "0" } & ActionResultV0)
  | ({ version: "1" } & ActionResultV1)
