// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionResultValue } from "./ActionResultValue"

export type ActionResultV1 = {
  /**
   * Primary text to display as the header of the response modal. e.g. "Success!", "Name Updated", or "Service Information", whatever makes sense
   */
  title: string
  /**
   * (optional) A general message for the user, just under the title
   */
  message: string | null
  /**
   * (optional) Structured data to present inside the modal
   */
  result: ActionResultValue | null
}
