// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActionResultV1 =
  | { type: "message"; message: string }
  | {
      type: "value"
      name: string
      value: string
      description: string | null
      copyable: boolean
      qr: boolean
      masked: boolean
    }
  | {
      type: "group"
      name: string
      value: Array<ActionResultV1>
      description?: string
    }
