// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionId } from "./ActionId"
import type { ActionRequestInput } from "./ActionRequestInput"
import type { ActionRequestTrigger } from "./ActionRequestTrigger"
import type { ActionSeverity } from "./ActionSeverity"
import type { PackageId } from "./PackageId"

export type ActionRequest = {
  packageId: PackageId
  actionId: ActionId
  severity: ActionSeverity
  reason?: string
  when?: ActionRequestTrigger
  input?: ActionRequestInput
}
