// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnySignature } from "./AnySignature"
import type { MerkleArchiveCommitment } from "./MerkleArchiveCommitment"

export type AddPackageParams = {
  url: string
  commitment: MerkleArchiveCommitment
  signature: AnySignature
}
