// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckPortRes } from './CheckPortRes'

export type AddPublicDomainRes = {
  dns: string | null
  port: Array<CheckPortRes>
}
