// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlpnInfo } from './AlpnInfo'
import type { ProxyAuth } from './ProxyAuth'

export type AddSslOptions = {
  preferredExternalPort: number
  addXForwardedHeaders: boolean
  alpn: AlpnInfo | null
  /**
   * Optional proxy-injected `Authorization` header for upstream requests.
   * When set, incoming requests are HTTP-parsed and an `Authorization`
   * header is added (or replaced) before being forwarded to the upstream
   * service. Setting this implies the connection must be HTTP-aware
   * (i.e. it is processed through `run_http_proxy`, the same path used
   * for `add_x_forwarded_headers`).
   */
  auth: ProxyAuth | null
}
