// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlpnInfo } from './AlpnInfo'
import type { ProxyAuth } from './ProxyAuth'

export type AddSslOptions = {
  preferredExternalPort: number
  /**
   * When `true`, the OS reverse proxy adds `X-Forwarded-Proto: https`
   * and `X-Forwarded-For: <client-ip>` to incoming HTTP requests before
   * forwarding them upstream. Setting this implies HTTP-aware proxying.
   */
  addXForwardedHeaders: boolean
  alpn: AlpnInfo | null
  /**
   * Optional reverse-proxy auth gate. When set, the OS reverse proxy
   * will validate the `Authorization` header on incoming HTTP requests
   * against this configuration before forwarding them upstream.
   * Unauthenticated requests get `401 Unauthorized` with an appropriate
   * `WWW-Authenticate` challenge. For `Basic`, the authenticated
   * username is forwarded to the upstream service as `X-Forwarded-User`.
   * Setting this implies HTTP-aware proxying.
   */
  auth: ProxyAuth | null
}
