// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocaleString } from "./LocaleString"

export type Alerts = {
  install: LocaleString | null
  uninstall: LocaleString | null
  restore: LocaleString | null
  start: LocaleString | null
  stop: LocaleString | null
}
