// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageBackupInfo } from './PackageBackupInfo'
import type { PackageId } from './PackageId'

export type BackupInfo = {
  version: string
  timestamp: string | null
  packageBackups: { [key: PackageId]: PackageBackupInfo }
}
