// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageBackupReport } from './PackageBackupReport'
import type { PackageId } from './PackageId'
import type { ServerBackupReport } from './ServerBackupReport'

export type BackupReport = {
  server: ServerBackupReport
  packages: { [key: PackageId]: PackageBackupReport }
}
