// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GatewayId } from './GatewayId'
import type { RangeGatewayAccess } from './RangeGatewayAccess'

export type BindingSetRangeGatewayAccessParams = {
  internalStartPort: number
  gateway: GatewayId
  access: RangeGatewayAccess
}
