// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BindOptions } from "./BindOptions"
import type { NetInfo } from "./NetInfo"

export type BindInfo = { enabled: boolean; options: BindOptions; net: NetInfo }
