// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddSslOptions } from "./AddSslOptions"
import type { HostId } from "./HostId"
import type { Security } from "./Security"

export type BindParams = {
  id: HostId
  internalPort: number
  preferredExternalPort: number
  addSsl: AddSslOptions | null
  secure: Security | null
}
