// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GatewayId } from "./GatewayId"

export type BindingGatewaySetEnabledParams = {
  internalPort: number
  gateway: GatewayId
  enabled: boolean | null
}
