// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthCheckId } from "./HealthCheckId"
import type { NamedHealthCheckResult } from "./NamedHealthCheckResult"
import type { PackageId } from "./PackageId"
import type { ReplayId } from "./ReplayId"
import type { TaskEntry } from "./TaskEntry"
import type { Version } from "./Version"

export type CheckDependenciesResult = {
  packageId: PackageId
  title: string | null
  installedVersion: Version | null
  satisfies: Array<Version>
  isRunning: boolean
  tasks: { [key: ReplayId]: TaskEntry }
  healthChecks: { [key: HealthCheckId]: NamedHealthCheckResult }
}
