// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceInterfaceId } from "./ServiceInterfaceId"

export type ClearServiceInterfacesParams = { except: Array<ServiceInterfaceId> }
