// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageId } from './PackageId'
import type { ReplayId } from './ReplayId'

export type ClearTaskParams = {
  packageId: PackageId
  replayId: ReplayId
  force: boolean
}
