// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionId } from "./ActionId"
import type { PackageId } from "./PackageId"
import type { ReplayId } from "./ReplayId"
import type { TaskInput } from "./TaskInput"
import type { TaskSeverity } from "./TaskSeverity"
import type { TaskTrigger } from "./TaskTrigger"

export type CreateTaskParams = {
  replayId: ReplayId
  packageId: PackageId
  actionId: ActionId
  severity: TaskSeverity
  reason?: string
  when?: TaskTrigger
  input?: TaskInput
}
