// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotificationLevel } from './NotificationLevel'

export type CreateNotificationParams = {
  level: NotificationLevel
  title: string
  message: string
  /**
   * Notification code. `0` is a generic notification (no data); `2` carries
   * a free-form string payload. `1` is reserved for backup-report
   * notifications generated by StartOS.
   */
  code: 0 | 2
  /**
   * Notification data. Shape depends on `code`: must be `null`/omitted for
   * code `0`, must be a string for code `2`.
   */
  data?: string | null
}
