// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeliveryAttempt = {
  subscriber: string
  at: string
  statusCode: number | null
  error: string | null
  durationMs: bigint
  replay: boolean
}
