// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthCheckId } from "./HealthCheckId"
import type { PackageId } from "./PackageId"

export type DependencyRequirement =
  | {
      kind: "running"
      id: PackageId
      healthChecks: Array<HealthCheckId>
      versionRange: string
    }
  | { kind: "exists"; id: PackageId; versionRange: string }
