// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LocaleString } from './LocaleString'
import type { MetadataSrc } from './MetadataSrc'

export type DepInfo = {
  description: LocaleString | null
  optional: boolean
} & MetadataSrc
