// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PathOrUrl } from "./PathOrUrl"

export type DepInfo = {
  description: string | null
  optional: boolean
  s9pk: PathOrUrl | null
}
