// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostnameInfo } from './HostnameInfo'

export type DerivedAddressInfo = {
  /**
   * User-controlled: private-gateway addresses the user has disabled
   */
  privateDisabled: Array<HostnameInfo>
  /**
   * User-controlled: public-gateway addresses the user has enabled
   */
  publicEnabled: Array<HostnameInfo>
  /**
   * COMPUTED: NetServiceData::update — all possible addresses for this binding
   */
  possible: Array<HostnameInfo>
}
