// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StartStop } from './StartStop'

export type DesiredStatus =
  | { main: 'stopped' }
  | { main: 'restarting' }
  | { main: 'running' }
  | { main: 'backing-up'; onComplete: StartStop }
