// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CountEntry } from './CountEntry'
import type { PackageVersionCount } from './PackageVersionCount'

export type DownloadsResponse = {
  totalRequests: bigint
  byPackage: Array<CountEntry>
  byPackageVersion: Array<PackageVersionCount>
}
