// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnyVerifyingKey } from "./AnyVerifyingKey"
import type { ContactInfo } from "./ContactInfo"
import type { Guid } from "./Guid"

export type EditSignerParams = {
  id: Guid
  setName: string | null
  addContact: Array<ContactInfo>
  addKey: Array<AnyVerifyingKey>
  removeContact: Array<ContactInfo>
  removeKey: Array<AnyVerifyingKey>
}
