// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetOsVersionParams = {
  sourceVersion: string | null
  targetVersion: string | null
  includePrerelease: boolean | null
  serverId: string | null
  platform: string | null
}
