// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostId } from "./HostId"
import type { PackageId } from "./PackageId"

export type GetServicePortForwardParams = {
  packageId?: PackageId
  hostId: HostId
  internalPort: number
}
