// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallbackId } from "./CallbackId"
import type { PackageId } from "./PackageId"

export type GetStoreParams = {
  packageId?: PackageId
  path: string
  callback?: CallbackId
}
