// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetUsersParams = {
  /**
   * Start of time range (RFC 3339)
   */
  after: string | null
  /**
   * End of time range (RFC 3339)
   */
  before: string | null
}
