// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeviceFilter } from "./DeviceFilter"

export type HardwareRequirements = {
  device: Array<DeviceFilter>
  ram: number | null
  arch: string[] | null
}
