// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BindInfo } from "./BindInfo"
import type { DomainConfig } from "./DomainConfig"
import type { HostKind } from "./HostKind"
import type { HostnameInfo } from "./HostnameInfo"

export type Host = {
  kind: HostKind
  bindings: { [key: number]: BindInfo }
  onions: string[]
  domains: { [key: string]: DomainConfig }
  /**
   * COMPUTED: NetService::update
   */
  hostnameInfo: { [key: number]: Array<HostnameInfo> }
}
