// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GatewayInfo } from './GatewayInfo'
import type { IpHostname } from './IpHostname'

export type HostnameInfo = {
  gateway: GatewayInfo
  public: boolean
  hostname: IpHostname
}
