// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IpHostname } from "./IpHostname"
import type { OnionHostname } from "./OnionHostname"

export type HostnameInfo =
  | {
      kind: "ip"
      networkInterfaceId: string
      public: boolean
      hostname: IpHostname
    }
  | { kind: "onion"; hostname: OnionHostname }
