// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostnameMetadata } from './HostnameMetadata'

export type HostnameInfo = {
  ssl: boolean
  public: boolean
  host: string
  port: number | null
  metadata: HostnameMetadata
}
