// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Bindings } from './Bindings'
import type { GatewayId } from './GatewayId'
import type { PortForward } from './PortForward'
import type { PublicDomainConfig } from './PublicDomainConfig'

export type Host = {
  bindings: Bindings
  publicDomains: { [key: string]: PublicDomainConfig }
  privateDomains: { [key: string]: Array<GatewayId> }
  /**
   * COMPUTED: port forwarding rules needed on gateways for public addresses to work.
   */
  portForwards: Array<PortForward>
}
