// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GatewayId } from './GatewayId'
import type { PackageId } from './PackageId'

export type HostnameMetadata =
  | { kind: 'ipv4'; gateway: GatewayId }
  | { kind: 'ipv6'; gateway: GatewayId; scopeId: number }
  | { kind: 'private-domain'; gateways: Array<GatewayId> }
  | { kind: 'public-domain'; gateway: GatewayId }
  | ({ kind: 'plugin'; package: PackageId } & { [key in string]?: unknown })
