// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImageSource =
  | "packed"
  | { dockerBuild: { workdir: string | null; dockerfile: string | null } }
  | { dockerTag: string }
