// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildArg } from "./BuildArg"

export type ImageSource =
  | "packed"
  | {
      dockerBuild: {
        workdir: string | null
        dockerfile: string | null
        buildArgs?: { [key: string]: BuildArg }
      }
    }
  | { dockerTag: string }
