// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ImageMetadata = {
  workdir: string
  user: string
  entrypoint: Array<string> | null
  cmd: Array<string> | null
}
