// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KeyboardOptions = {
  layout: string
  keymap: string | null
  model: string | null
  variant: string | null
  options: Array<string>
}
