// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A pre-V2 `StartOSBackups` folder found on a backup target. Surfaced so the
 * UI can warn (or refuse, when it wouldn't fit) before a new V2 backup runs.
 */
export type LegacyBackupInfo = { size: number; available: number }
