// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogEntry } from './LogEntry'

export type LogResponse = {
  entries: Array<LogEntry>
  startCursor: string | null
  endCursor: string | null
}
