// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Dependencies } from './Dependencies'
import type { Description } from './Description'
import type { GitHash } from './GitHash'
import type { HardwareRequirements } from './HardwareRequirements'
import type { ImageConfig } from './ImageConfig'
import type { ImageId } from './ImageId'
import type { LocaleString } from './LocaleString'
import type { PackageId } from './PackageId'
import type { PluginId } from './PluginId'
import type { Version } from './Version'
import type { VolumeId } from './VolumeId'

export type Manifest = {
  id: PackageId
  version: Version
  canMigrateTo: string
  canMigrateFrom: string
  images: { [key: ImageId]: ImageConfig }
  volumes: Array<VolumeId>
  dependencies: Dependencies
  hardwareRequirements: HardwareRequirements
  title: string
  description: Description
  releaseNotes: LocaleString
  gitHash: GitHash | null
  license: string
  packageRepo: string
  upstreamRepo: string
  marketingUrl: string
  donationUrl: string | null
  osVersion: string
  sdkVersion: string | null
  hardwareAcceleration: boolean
  /**
   * Mount /dev/fuse for fuse-overlayfs storage (the rootless storage
   * driver used by a nested OCI runtime).
   */
  userspaceFilesystems: boolean
  /**
   * Mount /dev/net/tun so the service can create kernel tunnel interfaces
   * (VPN / WireGuard / tun-class workloads).
   */
  virtualNetworking: boolean
  plugins: Array<PluginId>
  satisfies: Array<Version>
}
