// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Metadata } from './Metadata'
import type { PathOrUrl } from './PathOrUrl'

export type MetadataSrc = { metadata: Metadata } | { s9pk: PathOrUrl | null }
