// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GigaBytes } from "./GigaBytes"
import type { Percentage } from "./Percentage"

export type MetricsDisk = {
  percentageUsed: Percentage
  used: GigaBytes
  available: GigaBytes
  capacity: GigaBytes
}
