// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Percentage } from "./Percentage"

export type MetricsCpu = {
  percentageUsed: Percentage
  idle: Percentage
  userSpace: Percentage
  kernelSpace: Percentage
  wait: Percentage
}
