// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CountEntry } from './CountEntry'

export type MetricsSummary = {
  totalCheckins: bigint
  uniqueServers: bigint
  totalPackageRequests: bigint
  byArch: Array<CountEntry>
  byOsVersion: Array<CountEntry>
}
