// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MebiBytes } from "./MebiBytes"
import type { Percentage } from "./Percentage"

export type MetricsMemory = {
  percentageUsed: Percentage
  total: MebiBytes
  available: MebiBytes
  used: MebiBytes
  zramTotal: MebiBytes
  zramAvailable: MebiBytes
  zramUsed: MebiBytes
}
