// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricsCpu } from "./MetricsCpu"
import type { MetricsDisk } from "./MetricsDisk"
import type { MetricsGeneral } from "./MetricsGeneral"
import type { MetricsMemory } from "./MetricsMemory"

export type Metrics = {
  general: MetricsGeneral
  memory: MetricsMemory
  cpu: MetricsCpu
  disk: MetricsDisk
}
