// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileType } from "./FileType"
import type { PackageId } from "./PackageId"
import type { VolumeId } from "./VolumeId"

export type MountTarget = {
  packageId: PackageId
  volumeId: VolumeId
  subpath: string | null
  readonly: boolean
  filetype?: FileType
}
