// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NetInfo = {
  public: boolean
  assignedPort: number | null
  assignedSslPort: number | null
}
