// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IpInfo } from "./IpInfo"

export type NetworkInterfaceInfo = {
  name: string | null
  public: boolean | null
  secure: boolean | null
  ipInfo: IpInfo | null
}
