// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcmeProvider } from "./AcmeProvider"
import type { AcmeSettings } from "./AcmeSettings"
import type { Host } from "./Host"
import type { NetworkInterfaceInfo } from "./NetworkInterfaceInfo"
import type { WifiInfo } from "./WifiInfo"

export type NetworkInfo = {
  wifi: WifiInfo
  host: Host
  networkInterfaces: { [key: string]: NetworkInterfaceInfo }
  acme: { [key: AcmeProvider]: AcmeSettings }
}
