// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Alerts } from './Alerts'
import type { Description } from './Description'
import type { GitHash } from './GitHash'
import type { LocaleString } from './LocaleString'
import type { PluginId } from './PluginId'
import type { Version } from './Version'

export type PackageMetadata = {
  title: string
  description: Description
  releaseNotes: LocaleString
  gitHash: GitHash | null
  license: string
  packageRepo: string
  upstreamRepo: string
  marketingUrl: string
  donationUrl: string | null
  alerts: Alerts
  osVersion: string
  sdkVersion: string | null
  hardwareAcceleration: boolean
  nestedRuntime: boolean
  plugins: Array<PluginId>
  satisfies: Array<Version>
}
