// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageId } from './PackageId'
import type { PackageMetadata } from './PackageMetadata'
import type { Version } from './Version'

export type PackageVersionAddData = {
  packageId: PackageId
  version: Version
  isFirstVersion: boolean
  isUpdate: boolean
  urls: string[]
  metadata: PackageMetadata
}
