// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstalledState } from "./InstalledState"
import type { InstallingState } from "./InstallingState"
import type { UpdatingState } from "./UpdatingState"

export type PackageState =
  | ({ state: "installing" } & InstallingState)
  | ({ state: "restoring" } & InstallingState)
  | ({ state: "updating" } & UpdatingState)
  | ({ state: "installed" } & InstalledState)
  | ({ state: "removing" } & InstalledState)
