// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Alerts } from './Alerts'
import type { DataUrl } from './DataUrl'
import type { DependencyMetadata } from './DependencyMetadata'
import type { Description } from './Description'
import type { GitHash } from './GitHash'
import type { HardwareRequirements } from './HardwareRequirements'
import type { LocaleString } from './LocaleString'
import type { MerkleArchiveCommitment } from './MerkleArchiveCommitment'
import type { PackageId } from './PackageId'
import type { RegistryAsset } from './RegistryAsset'

export type PackageVersionInfo = {
  sourceVersion: string | null
  s9pks: Array<[HardwareRequirements, RegistryAsset<MerkleArchiveCommitment>]>
  title: string
  icon: DataUrl
  description: Description
  releaseNotes: LocaleString
  gitHash: GitHash | null
  license: string
  wrapperRepo: string
  upstreamRepo: string
  supportSite: string
  marketingSite: string
  donationUrl: string | null
  docsUrl: string | null
  alerts: Alerts
  dependencyMetadata: { [key: PackageId]: DependencyMetadata }
  osVersion: string
  sdkVersion: string | null
  hardwareAcceleration: boolean
}
