// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UrlPluginRegistration } from './UrlPluginRegistration'

export type PackagePlugin = { url: UrlPluginRegistration | null }
