// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Alerts } from './Alerts'
import type { DataUrl } from './DataUrl'
import type { DependencyMetadata } from './DependencyMetadata'
import type { Description } from './Description'
import type { GitHash } from './GitHash'
import type { HardwareRequirements } from './HardwareRequirements'
import type { LocaleString } from './LocaleString'
import type { MerkleArchiveCommitment } from './MerkleArchiveCommitment'
import type { PackageId } from './PackageId'
import type { PluginId } from './PluginId'
import type { RegistryAsset } from './RegistryAsset'
import type { Version } from './Version'

export type PackageVersionInfo = {
  icon: DataUrl
  dependencyMetadata: { [key: PackageId]: DependencyMetadata }
  sourceVersion: string | null
  s9pks: Array<[HardwareRequirements, RegistryAsset<MerkleArchiveCommitment>]>
  title: string
  description: Description
  releaseNotes: LocaleString
  gitHash: GitHash | null
  license: string
  packageRepo: string
  upstreamRepo: string
  marketingUrl: string
  donationUrl: string | null
  docsUrls: string[]
  alerts: Alerts
  osVersion: string
  sdkVersion: string | null
  hardwareAcceleration: boolean
  plugins: Array<PluginId>
  satisfies: Array<Version>
}
