// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StartOsRecoveryInfo } from './StartOsRecoveryInfo'

export type PartitionInfo = {
  logicalname: string
  label: string | null
  capacity: number
  used: number | null
  startOs: { [key: string]: StartOsRecoveryInfo }
  guid: string | null
  filesystem: string | null
}
