// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostId } from './HostId'
import type { PackageId } from './PackageId'

export type PluginHostnameInfo = {
  packageId: PackageId | null
  hostId: HostId
  internalPort: number
  ssl: boolean
  public: boolean
  hostname: string
  port: number | null
  info: unknown
}
