// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProxyInfo } from "./ProxyInfo"

export type Proxies = { [key: number]: ProxyInfo }
