// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Authorization header to inject on upstream proxied requests.
 *
 * - `Bearer { token }` -> `Authorization: Bearer <token>`
 * - `Basic  { username, password }` -> `Authorization: Basic <base64(username:password)>`
 */
export type ProxyAuth =
  | { type: 'bearer'; token: string }
  | { type: 'basic'; username: string; password: string }
