// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GatewayId } from './GatewayId'
import type { RangeGatewayAccess } from './RangeGatewayAccess'

/**
 * Contiguous port-range binding (e.g. WebRTC/STUN/TURN RTP ranges).
 *
 * Keyed by `internal_start_port` in [`BindingRanges`]. The range covers
 * `internal_start_port..(internal_start_port + number_of_ports)` and is
 * forwarded through a single iptables rule per protocol per gateway,
 * preserving the destination port number.
 */
export type RangeBindInfo = {
  enabled: boolean
  externalStartPort: number
  numberOfPorts: number
  /**
   * Per-gateway exposure chosen by the operator. Absent gateways default to
   * [`RangeGatewayAccess::Lan`] (LAN-only), so a freshly-bound range is
   * not exposed to the WAN until the operator opts in. Persisted
   * independently of `enabled` (the service-lifecycle flag) so operator
   * choices survive restarts / rebinds.
   */
  gatewayAccess: { [key: GatewayId]: RangeGatewayAccess }
}
