// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-gateway exposure of a port range, chosen by the operator.
 *
 * Mirrors how single-port bindings treat WAN vs LAN addresses in
 * [`crate::net::forward::ForwardRequirements`]: `LanWan` puts the gateway in
 * `public_gateways` (no source filter → reachable from LAN and WAN), `Lan`
 * puts the gateway's subnet(s) in `private_ips` (source filtered to the LAN →
 * reachable from LAN only), and `Disabled` forwards on neither.
 */
export type RangeGatewayAccess = 'disabled' | 'lan' | 'lan-wan'
