// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Guid } from './Guid'
import type { RegistryEventData } from './RegistryEventData'

export type RegistryEvent = { id: Guid; occurredAt: string } & RegistryEventData
