// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnySignature } from "./AnySignature"
import type { AnyVerifyingKey } from "./AnyVerifyingKey"

export type RegistryAsset<Commitment> = {
  publishedAt: string
  url: string
  commitment: Commitment
  signatures: { [key: AnyVerifyingKey]: AnySignature }
}
