// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OsVersionAddData } from './OsVersionAddData'
import type { OsVersionRemoveData } from './OsVersionRemoveData'
import type { PackageRemoveData } from './PackageRemoveData'
import type { PackageVersionAddData } from './PackageVersionAddData'

export type RegistryEventData =
  | { topic: 'package.version.add'; data: PackageVersionAddData }
  | { topic: 'package.remove'; data: PackageRemoveData }
  | { topic: 'os.version.add'; data: OsVersionAddData }
  | { topic: 'os.version.remove'; data: OsVersionRemoveData }
