// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Base64 } from './Base64'
import type { PackageId } from './PackageId'
import type { Version } from './Version'

export type RemovePackageParams = {
  id: PackageId
  version: Version
  sighash: Base64 | null
}
