// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Base64 } from "./Base64"

export type RequestCommitment = {
  timestamp: number
  nonce: number
  size: number
  blake3: Base64
}
