// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcmeSettings } from "./AcmeSettings"
import type { Governor } from "./Governor"
import type { IpInfo } from "./IpInfo"
import type { LshwDevice } from "./LshwDevice"
import type { ServerStatus } from "./ServerStatus"
import type { SmtpValue } from "./SmtpValue"
import type { WifiInfo } from "./WifiInfo"

export type ServerInfo = {
  arch: string
  platform: string
  id: string
  hostname: string
  version: string
  packageVersionCompat: string
  postInitMigrationTodos: string[]
  lastBackup: string | null
  lanAddress: string
  onionAddress: string
  /**
   * for backwards compatibility
   */
  torAddress: string
  ipInfo: { [key: string]: IpInfo }
  acme: AcmeSettings | null
  statusInfo: ServerStatus
  wifi: WifiInfo
  unreadNotificationCount: number
  passwordHash: string
  pubkey: string
  caFingerprint: string
  ntpSynced: boolean
  zram: boolean
  governor: Governor | null
  smtp: SmtpValue | null
  ram: number
  devices: Array<LshwDevice>
}
