// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Governor } from './Governor'
import type { KeyboardOptions } from './KeyboardOptions'
import type { LshwDevice } from './LshwDevice'
import type { NetworkInfo } from './NetworkInfo'
import type { ServerStatus } from './ServerStatus'
import type { SmtpValue } from './SmtpValue'

export type ServerInfo = {
  arch: string
  platform: string
  id: string
  name: string
  hostname: string
  version: string
  packageVersionCompat: string
  postInitMigrationTodos: Record<string, unknown>
  lastBackup: string | null
  network: NetworkInfo
  statusInfo: ServerStatus
  unreadNotificationCount: number
  passwordHash: string
  pubkey: string
  caFingerprint: string
  ntpSynced: boolean
  zram: boolean
  governor: Governor | null
  smtp: SmtpValue | null
  echoipUrls: string[]
  ram: number
  devices: Array<LshwDevice>
  kiosk: boolean | null
  language: string | null
  keyboard: KeyboardOptions | null
}
