// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressInfo } from "./AddressInfo"
import type { ServiceInterfaceId } from "./ServiceInterfaceId"
import type { ServiceInterfaceType } from "./ServiceInterfaceType"

export type ServiceInterface = {
  id: ServiceInterfaceId
  name: string
  description: string
  hasPrimary: boolean
  masked: boolean
  addressInfo: AddressInfo
  type: ServiceInterfaceType
}
