// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetupInfo } from "./SetupInfo"
import type { SetupProgress } from "./SetupProgress"
import type { SetupResult } from "./SetupResult"

export type SetupStatusRes =
  | { status: "needs-install" }
  | ({ status: "incomplete" } & SetupInfo)
  | ({ status: "running" } & SetupProgress)
  | ({ status: "complete" } & SetupResult)
