// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetupInfo = {
  guid: string | null
  attach: boolean
  mokEnrolled: boolean
  /**
   * The whole disk the running OS booted from. Set when the device is
   * pre-installed (setup-after-install), so the wizard fixes it as the OS
   * drive and asks only for a data drive.
   */
  osDrive: string | null
}
