// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetupProgress } from "./SetupProgress"
import type { SetupResult } from "./SetupResult"

export type SetupStatusRes =
  | ({ status: "complete" } & SetupResult)
  | ({ status: "running" } & SetupProgress)
