// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetupResult = {
  torAddresses: Array<string>
  hostname: string
  lanAddress: string
  rootCa: string
}
