// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnyVerifyingKey } from "./AnyVerifyingKey"
import type { ContactInfo } from "./ContactInfo"

export type SignerInfo = {
  name: string
  contact: Array<ContactInfo>
  keys: Array<AnyVerifyingKey>
}
