// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SmtpSecurity } from './SmtpSecurity'

export type SmtpValue = {
  host: string
  port: number
  from: string
  username: string
  password: string | null
  security: SmtpSecurity
}
