// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ssid are the names of the wifis, usually human readable.
 */
export type Ssid = string
