// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServerHostname } from './ServerHostname'

export type StartOsRecoveryInfo = {
  hostname: ServerHostname
  version: string
  timestamp: string
  passwordHash: string | null
  wrappedKey: string | null
}
