// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Hostname } from './Hostname'

export type StartOsRecoveryInfo = {
  hostname: Hostname
  version: string
  timestamp: string
  passwordHash: string | null
  wrappedKey: string | null
}
