// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TestSmtpParams = {
  server: string
  port: number
  from: string
  to: string
  login: string
  password: string | null
}
