// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InstallingInfo } from "./InstallingInfo"
import type { Manifest } from "./Manifest"

export type UpdatingState = {
  manifest: Manifest
  installingInfo: InstallingInfo
}
