// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginHostnameInfo } from './PluginHostnameInfo'

export type UrlPluginClearUrlsParams = { except: Array<PluginHostnameInfo> }
