// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EncryptedWire } from "./EncryptedWire"

export type VerifyCifsParams = {
  hostname: string
  path: string
  username: string
  password: EncryptedWire | null
}
