// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignalStrength } from './SignalStrength'
import type { Ssid } from './Ssid'
import type { WifiListOut } from './WifiListOut'

export type WifiListInfo = {
  ssids: { [key: Ssid]: SignalStrength }
  connected: Ssid | null
  country: string | null
  ethernet: boolean
  availableWifi: Array<WifiListOut>
}
