// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionVisibility } from "./ActionVisibility"
import type { AllowedStatuses } from "./AllowedStatuses"

export type ActionMetadata = {
  name: string
  description: string
  warning: string | null
  visibility: ActionVisibility
  allowedStatuses: AllowedStatuses
  group: string | null
}
