// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionId } from "./ActionId"
import type { ActionRequestCondition } from "./ActionRequestCondition"
import type { ActionRequestInput } from "./ActionRequestInput"

export type ActionRequest = {
  id: ActionId
  if: ActionRequestCondition | null
  input: ActionRequestInput | null
}
