// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionId } from "./ActionId"
import type { ActionRequestInput } from "./ActionRequestInput"
import type { ActionRequestTrigger } from "./ActionRequestTrigger"

export type ActionRequest = {
  id: ActionId
  when: ActionRequestTrigger | null
  input: ActionRequestInput | null
}
