// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Signature } from "./Signature"
import type { SignerKey } from "./SignerKey"

export type AddAssetParams = {
  url: string
  signature: Signature
  version: string
  platform: string
  upload: boolean
  __auth_signer: SignerKey
}
