// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Signature } from "./Signature"

export type AddParams = {
  url: string
  signature: Signature
  version: string
  platform: string
  upload: boolean
}
