// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Version } from "./Version"

export type AddVersionParams = {
  version: Version
  headline: string
  releaseNotes: string
  sourceVersion: string
}
