// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddSslOptions } from "./AddSslOptions"
import type { Security } from "./Security"

export type BindOptions = {
  scheme: string | null
  preferredExternalPort: number
  addSsl: AddSslOptions | null
  secure: Security | null
}
