// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddSslOptions } from "./AddSslOptions";
import type { HostId } from "./HostId";
import type { HostKind } from "./HostKind";
import type { Security } from "./Security";

export type BindParams = {
  kind: HostKind;
  id: HostId;
  internalPort: number;
  scheme: string | null;
  preferredExternalPort: number;
  addSsl: AddSslOptions | null;
  secure: Security | null;
};
