// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Base64 } from "./Base64"
import type { Pem } from "./Pem"

export type Blake3Ed2551SignatureInfo = {
  context: string
  hash: Base64
  size: bigint
  signatures: { [key: Pem]: Base64 }
}
