// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthCheckId } from "./HealthCheckId"
import type { HealthCheckResult } from "./HealthCheckResult"
import type { PackageId } from "./PackageId"

export type CheckDependenciesResult = {
  packageId: PackageId
  isInstalled: boolean
  isRunning: boolean
  configSatisfied: boolean
  healthChecks: { [key: HealthCheckId]: HealthCheckResult }
  version: string | null
}
