// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthCheckResult } from "./HealthCheckResult"

export type CheckDependenciesResult = {
  packageId: string
  isInstalled: boolean
  isRunning: boolean
  healthChecks: Array<HealthCheckResult>
}
