// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HealthCheckId } from "./HealthCheckId"
import type { NamedHealthCheckResult } from "./NamedHealthCheckResult"
import type { PackageId } from "./PackageId"

export type CheckDependenciesResult = {
  packageId: PackageId
  title: string | null
  installedVersion: string | null
  satisfies: string[]
  isRunning: boolean
  inputSpecSatisfied: boolean
  healthChecks: { [key: HealthCheckId]: NamedHealthCheckResult }
}
