// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputSpecSpec } from "./InputSpecSpec"

export type InputSpecRes = {
  inputSpec: Record<string, unknown> | null
  spec: InputSpecSpec
}
