// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionRequest } from "./ActionRequest"
import type { DataUrl } from "./DataUrl"

export type CurrentDependencyInfo = {
  title: string | null
  icon: DataUrl | null
  versionRange: string
  requestedActions: { [key: string]: ActionRequest }
} & (
  | { kind: "optional" }
  | { kind: "exists" }
  | { kind: "running"; healthChecks: string[] }
)
