// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataUrl } from "./DataUrl"

export type DependencyMetadata = {
  title: string | null
  icon: DataUrl | null
  description: string | null
  optional: boolean
}
