// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExportedOnionHostname = {
  value: string
  port: number | null
  sslPort: number | null
}
