// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionId } from "./ActionId"
import type { ActionMetadata } from "./ActionMetadata"
import type { PackageId } from "./PackageId"

export type ExportActionParams = {
  packageId?: PackageId
  id: ActionId
  metadata: ActionMetadata
}
