// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportedIpHostname } from "./ExportedIpHostname"
import type { ExportedOnionHostname } from "./ExportedOnionHostname"

export type ExportedHostnameInfo =
  | {
      kind: "ip"
      networkInterfaceId: string
      public: boolean
      hostname: ExportedIpHostname
    }
  | { kind: "onion"; hostname: ExportedOnionHostname }
