// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OsIndex } from "./OsIndex"
import type { SignerInfo } from "./SignerInfo"

export type FullIndex = { os: OsIndex; signers: { [key: string]: SignerInfo } }
