// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallbackId } from "./CallbackId"
import type { HostId } from "./HostId"
import type { PackageId } from "./PackageId"

export type GetHostInfoParams = {
  hostId: HostId
  packageId?: PackageId
  callback?: CallbackId
}
