// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Callback } from "./Callback";
import type { GetHostInfoParamsKind } from "./GetHostInfoParamsKind";

export type GetHostInfoParams = {
  kind: GetHostInfoParamsKind | null;
  serviceInterfaceId: string;
  packageId: string | null;
  callback: Callback;
};
