// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Callback } from "./Callback"
import type { HostId } from "./HostId"

export type GetHostInfoParams = {
  hostId: HostId
  packageId: string | null
  callback: Callback
}
