// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GetOsVersionParams = {
  source: string | null
  target: string | null
  serverId: string | null
  arch: string | null
}
