// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageDetailLevel } from "./PackageDetailLevel"
import type { PackageId } from "./PackageId"

export type GetPackageParams = {
  id: PackageId | null
  version: string | null
  sourceVersion: string | null
  otherVersions: PackageDetailLevel | null
}
