// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Callback } from "./Callback"
import type { ServiceInterfaceId } from "./ServiceInterfaceId"

export type GetPrimaryUrlParams = {
  packageId: string | null
  serviceInterfaceId: ServiceInterfaceId
  callback: Callback
}
