// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallbackId } from "./CallbackId"
import type { ServiceInterfaceId } from "./ServiceInterfaceId"

export type GetServiceInterfaceParams = {
  packageId: string | null
  serviceInterfaceId: ServiceInterfaceId
  callback: CallbackId
}
