// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Algorithm } from "./Algorithm";

export type GetSslCertificateParams = {
  packageId: string | null;
  hostId: string;
  algorithm: Algorithm | null;
};
