// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Algorithm } from "./Algorithm"
import type { CallbackId } from "./CallbackId"

export type GetSslCertificateParams = {
  hostnames: string[]
  algorithm?: Algorithm
  callback: CallbackId | null
}
