// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Host } from "./Host";
import type { HostId } from "./HostId";

export type HostInfo = { [key: HostId]: Host };
