// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageSource } from "./ImageSource"

export type ImageConfig = {
  source: ImageSource
  arch: string[]
  emulateMissingAs: string | null
}
