// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FullProgress } from "./FullProgress";
import type { Manifest } from "./Manifest";

export type InstallingInfo = { newManifest: Manifest; progress: FullProgress };
