// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IpInfo = {
  ipv4Range: string | null
  ipv4: string | null
  ipv6Range: string | null
  ipv6: string | null
}
