// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallbackId } from "./CallbackId"

export type ListServiceInterfacesParams = {
  packageId: string | null
  callback: CallbackId
}
