// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Base64 } from "./Base64"

export type MerkleArchiveCommitment = {
  rootSighash: Base64
  rootMaxsize: number
}
