// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OsVersionInfo } from "./OsVersionInfo"
import type { SignerInfo } from "./SignerInfo"

export type OsIndex = {
  signers: Array<SignerInfo>
  versions: { [key: string]: OsVersionInfo }
}
