// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OsVersionInfo } from "./OsVersionInfo"
import type { Version } from "./Version"

export type OsIndex = { versions: { [key: Version]: OsVersionInfo } }
