// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegistryAsset } from "./RegistryAsset"

export type OsVersionInfo = {
  headline: string
  releaseNotes: string
  sourceVersion: string
  signers: string[]
  iso: { [key: string]: RegistryAsset }
  squashfs: { [key: string]: RegistryAsset }
  img: { [key: string]: RegistryAsset }
}
