// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataUrl } from "./DataUrl"
import type { Description } from "./Description"
import type { MerkleArchiveCommitment } from "./MerkleArchiveCommitment"
import type { RegistryAsset } from "./RegistryAsset"

export type PackageInfo = {
  title: string
  icon: DataUrl
  description: Description
  gitHash: string
  license: string
  wrapperRepo: string
  upstreamRepo: string
  supportSite: string
  marketingSite: string
  s9pk: RegistryAsset<MerkleArchiveCommitment>
}
