// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignatureInfo } from "./SignatureInfo"

export type RegistryAsset = { url: string; signatureInfo: SignatureInfo }
