// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReverseProxyBind } from "./ReverseProxyBind"
import type { ReverseProxyDestination } from "./ReverseProxyDestination"
import type { ReverseProxyHttp } from "./ReverseProxyHttp"

export type ReverseProxyParams = {
  bind: ReverseProxyBind
  dst: ReverseProxyDestination
  http: ReverseProxyHttp
}
