// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnySignature } from "./AnySignature"
import type { Version } from "./Version"

export type SignAssetParams = {
  version: Version
  platform: string
  signature: AnySignature
}
