// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContactInfo } from "./ContactInfo"
import type { SignerKey } from "./SignerKey"

export type SignerInfo = {
  name: string
  contact: Array<ContactInfo>
  keys: Array<SignerKey>
}
