// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Blake3Ed25519Signature } from "./Blake3Ed25519Signature"

export type Signature = { blake3Ed25519: Blake3Ed25519Signature }
