// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Blake3Ed2551SignatureInfo } from "./Blake3Ed2551SignatureInfo"

export type SignatureInfo = {
  context: string
  "blake-3-ed-25-5i-9": Blake3Ed2551SignatureInfo | null
}
