// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Guid } from "./Guid"
import type { Version } from "./Version"

export type VersionSignerParams = { version: Version; signer: Guid }
