.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-auth-get-pubkey 1  "get-pubkey " 
.SH NAME
start\-tunnel\-auth\-get\-pubkey \- Get the public key from the server
.SH SYNOPSIS
\fBstart\-tunnel auth get\-pubkey\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Get the public key from the server
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
