.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-port-forward-remove 1  "remove " 
.SH NAME
start\-tunnel\-port\-forward\-remove \- Remove port forward
.SH SYNOPSIS
\fBstart\-tunnel port\-forward remove\fR [\fB\-\-hostname\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fISOURCE\fR> 
.SH DESCRIPTION
Remove port forward
.SH OPTIONS
.TP
\fB\-\-hostname\fR \fI<HOSTNAME>\fR
Remove a single SNI route on `source`; omit to remove the whole forward
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISOURCE\fR>

