.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-subnet-set-wan 1  "set-wan " 
.SH NAME
start\-tunnel\-subnet\-set\-wan \- Assign the WAN IP a subnet\*(Aqs traffic uses
.SH SYNOPSIS
\fBstart\-tunnel subnet set\-wan\fR [\fB\-\-wan\-ip\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fISUBNET\fR> 
.SH DESCRIPTION
Assign the WAN IP a subnet\*(Aqs traffic uses
.SH OPTIONS
.TP
\fB\-\-wan\-ip\fR \fI<WAN_IP>\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISUBNET\fR>

