.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-dns-add 1  "add " 
.SH NAME
start\-tunnel\-dns\-add \- Add or replace a DNS record
.SH SYNOPSIS
\fBstart\-tunnel dns add\fR <\fB\-\-type\fR> [\fB\-\-ttl\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> <\fIVALUE\fR> 
.SH DESCRIPTION
Add or replace a DNS record
.SH OPTIONS
.TP
\fB\-\-type\fR \fI<RTYPE>\fR

.TP
\fB\-\-ttl\fR \fI<TTL>\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>

.TP
<\fIVALUE\fR>

