.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-device-set-wan 1  "set-wan " 
.SH NAME
start\-tunnel\-device\-set\-wan \- Override the WAN IP for a single device
.SH SYNOPSIS
\fBstart\-tunnel device set\-wan\fR [\fB\-\-wan\-ip\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fISUBNET\fR> <\fIIP\fR> 
.SH DESCRIPTION
Override the WAN IP for a single device
.SH OPTIONS
.TP
\fB\-\-wan\-ip\fR \fI<WAN_IP>\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISUBNET\fR>

.TP
<\fIIP\fR>

