.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-device-set-kind 1  "set-kind " 
.SH NAME
start\-tunnel\-device\-set\-kind \- Promote a device to a server or demote it to a client
.SH SYNOPSIS
\fBstart\-tunnel device set\-kind\fR <\fB\-\-kind\fR> [\fB\-h\fR|\fB\-\-help\fR] <\fISUBNET\fR> <\fIIP\fR> 
.SH DESCRIPTION
Promote a device to a server or demote it to a client
.SH OPTIONS
.TP
\fB\-\-kind\fR \fI<KIND>\fR

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
client
.IP \(bu 2
server
.RE
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISUBNET\fR>

.TP
<\fIIP\fR>

