.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-port-forward-add 1  "add " 
.SH NAME
start\-tunnel\-port\-forward\-add \- Add a new port forward
.SH SYNOPSIS
\fBstart\-tunnel port\-forward add\fR [\fB\-\-label\fR] [\fB\-\-sni\fR] [\fB\-\-count\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIEXTERNAL_PORT\fR> <\fITARGET\fR> 
.SH DESCRIPTION
Add a new port forward
.SH OPTIONS
.TP
\fB\-\-label\fR \fI<LABEL>\fR

.TP
\fB\-\-sni\fR \fI<SNI>\fR
Hostnames to SNI\-demux on the shared external port. Empty = normal DNAT
.TP
\fB\-\-count\fR \fI<COUNT>\fR
Number of contiguous ports to forward (a PCP PORT_SET range), counting up from both `external_port` and the target port. Defaults to 1. Not valid together with SNI demux
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIEXTERNAL_PORT\fR>
External (WAN) port to forward. The external IP is fixed to the target\*(Aqs WAN so return traffic stays symmetric
.TP
<\fITARGET\fR>

