.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-web-import-certificate 1  "import-certificate " 
.SH NAME
start\-tunnel\-web\-import\-certificate \- Import a certificate for the webserver
.SH SYNOPSIS
\fBstart\-tunnel web import\-certificate\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Import a certificate for the webserver
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
