.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-device-set-auto-port-forward 1  "set-auto-port-forward " 
.SH NAME
start\-tunnel\-device\-set\-auto\-port\-forward \- Allow or deny a device to auto\-create port forwards
.SH SYNOPSIS
\fBstart\-tunnel device set\-auto\-port\-forward\fR [\fB\-\-enabled\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fISUBNET\fR> <\fIIP\fR> 
.SH DESCRIPTION
Allow or deny a device to auto\-create port forwards
.SH OPTIONS
.TP
\fB\-\-enabled\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISUBNET\fR>

.TP
<\fIIP\fR>

