.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-web-generate-certificate 1  "generate-certificate " 
.SH NAME
start\-tunnel\-web\-generate\-certificate \- Generate a certificate for the webserver
.SH SYNOPSIS
\fBstart\-tunnel web generate\-certificate\fR [\fB\-h\fR|\fB\-\-help\fR] [\fISUBJECT\fR] 
.SH DESCRIPTION
Generate a certificate for the webserver
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fISUBJECT\fR]
Subject Alternative Name(s) for certificate
