.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-registry-os-asset-get-img 1  "img " 
.SH NAME
start\-registry\-os\-asset\-get\-img \- Download IMG file
.SH SYNOPSIS
\fBstart\-registry os asset get img\fR [\fB\-d\fR|\fB\-\-download\fR] [\fB\-r\fR|\fB\-\-reverify\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIVERSION\fR> <\fIPLATFORM\fR> 
.SH DESCRIPTION
Download IMG file
.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-download\fR \fI<DOWNLOAD>\fR
Directory path to download to
.TP
\fB\-r\fR, \fB\-\-reverify\fR
Verify hash after download completes
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIVERSION\fR>
StartOS version number
.TP
<\fIPLATFORM\fR>
Target platform identifier
