// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostnameInfo } from './HostnameInfo'

export type DerivedAddressInfo = {
  /**
   * User override: enable these addresses (only for public IP & port)
   */
  enabled: Array<string>
  /**
   * User override: disable these addresses (only for domains and private IP & port)
   */
  disabled: Array<[string, number]>
  /**
   * COMPUTED: NetServiceData::update — all possible addresses for this binding
   */
  available: Array<HostnameInfo>
}
