// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotificationLevel } from './NotificationLevel'
import type { PackageId } from './PackageId'

export type Notification = {
  packageId: PackageId | null
  createdAt: string
  code: number
  level: NotificationLevel
  title: string
  message: string
  data: any
  seen: boolean
}
