.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-registry-os-asset-add 1  "add " 
.SH NAME
start\-registry\-os\-asset\-add \- Add asset to registry
.SH SYNOPSIS
\fBstart\-registry os asset add\fR <\fB\-p\fR|\fB\-\-platform\fR> <\fB\-v\fR|\fB\-\-version\fR> [\fB\-h\fR|\fB\-\-help\fR] <\fIFILE\fR> <\fIURL\fR> 
.SH DESCRIPTION
Add asset to registry
.SH OPTIONS
.TP
\fB\-p\fR, \fB\-\-platform\fR \fI<PLATFORM>\fR
Target platform identifier
.TP
\fB\-v\fR, \fB\-\-version\fR \fI<VERSION>\fR
StartOS version number
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFILE\fR>
Path to the asset file
.TP
<\fIURL\fR>
URL of the asset
