.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-registry-package-add 1  "add " 
.SH NAME
start\-registry\-package\-add \- Add package to registry index
.SH SYNOPSIS
\fBstart\-registry package add\fR [\fB\-\-url\fR] [\fB\-\-no\-verify\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIFILE\fR> 
.SH DESCRIPTION
Add package to registry index
.SH OPTIONS
.TP
\fB\-\-url\fR \fI<URL>\fR
URL of the package
.TP
\fB\-\-no\-verify\fR
Skip signature verification
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFILE\fR>
Path to s9pk package file
