.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-registry-metrics-downloads 1  "downloads " 
.SH NAME
start\-registry\-metrics\-downloads \- Count package download requests with optional filters
.SH SYNOPSIS
\fBstart\-registry metrics downloads\fR [\fB\-\-pkg\-id\fR] [\fB\-\-version\fR] [\fB\-\-after\fR] [\fB\-\-before\fR] [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Count package download requests with optional filters
.SH OPTIONS
.TP
\fB\-\-pkg\-id\fR \fI<PKG_ID>\fR
Filter by package ID
.TP
\fB\-\-version\fR \fI<VERSION>\fR
Filter by version
.TP
\fB\-\-after\fR \fI<AFTER>\fR
Start of time range (RFC 3339 timestamp)
.TP
\fB\-\-before\fR \fI<BEFORE>\fR
End of time range (RFC 3339 timestamp)
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
