.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-registry-admin-signer 1  "signer " 
.SH NAME
start\-registry\-admin\-signer \- Commands to add or list signers
.SH SYNOPSIS
\fBstart\-registry admin signer\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Commands to add or list signers
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-registry\-admin\-signer\-add(1)
Add signer
.TP
start\-registry\-admin\-signer\-edit(1)
Edit signer information
.TP
start\-registry\-admin\-signer\-list(1)
List signers
