.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-registry-package-category-list 1  "list " 
.SH NAME
start\-registry\-package\-category\-list \- List registry categories
.SH SYNOPSIS
\fBstart\-registry package category list\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List registry categories
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
