.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-registry-package-category 1  "category " 
.SH NAME
start\-registry\-package\-category \- Update categories in registry
.SH SYNOPSIS
\fBstart\-registry package category\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Update categories in registry
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-registry\-package\-category\-add(1)
Add a category to the registry
.TP
start\-registry\-package\-category\-add\-package(1)
Add a package to a category
.TP
start\-registry\-package\-category\-list(1)
List registry categories
.TP
start\-registry\-package\-category\-remove(1)
Remove category from registry
.TP
start\-registry\-package\-category\-remove\-package(1)
Remove package from category
