.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-registry-package-category-remove 1  "remove " 
.SH NAME
start\-registry\-package\-category\-remove \- Remove category from registry
.SH SYNOPSIS
\fBstart\-registry package category remove\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR> 
.SH DESCRIPTION
Remove category from registry
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>

