.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-registry-db 1  "db " 
.SH NAME
start\-registry\-db \- Commands to interact with the db i.e. dump and apply
.SH SYNOPSIS
\fBstart\-registry db\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Commands to interact with the db i.e. dump and apply
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-registry\-db\-apply(1)
Update a database record
.TP
start\-registry\-db\-dump(1)
Filter and query the database
