.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-registry-os-version-get 1  "get " 
.SH NAME
start\-registry\-os\-version\-get \- Get OS versions info
.SH SYNOPSIS
\fBstart\-registry os version get\fR [\fB\-\-src\fR] [\fB\-\-target\-version\fR] [\fB\-\-id\fR] [\fB\-\-platform\fR] [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Get OS versions info
.SH OPTIONS
.TP
\fB\-\-src\fR \fI<SOURCE_VERSION>\fR
Source version to upgrade from
.TP
\fB\-\-target\-version\fR \fI<TARGET_VERSION>\fR
Target version range constraint
.TP
\fB\-\-id\fR \fI<SERVER_ID>\fR
Unique server identifier
.TP
\fB\-\-platform\fR \fI<PLATFORM>\fR
Target platform identifier
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
