.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-registry-os 1  "os " 
.SH NAME
start\-registry\-os \- Commands related to OS assets and versions
.SH SYNOPSIS
\fBstart\-registry os\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Commands related to OS assets and versions
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-registry\-os\-asset(1)
Commands to add, sign, or get registry assets
.TP
start\-registry\-os\-index(1)
List OS versions index
.TP
start\-registry\-os\-promote(1)
Promote an OS version from one registry to another
.TP
start\-registry\-os\-version(1)
Commands to add, remove, or list versions or version signers
