.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-registry-os-asset-sign 1  "sign " 
.SH NAME
start\-registry\-os\-asset\-sign \- Sign file and add to registry
.SH SYNOPSIS
\fBstart\-registry os asset sign\fR <\fB\-p\fR|\fB\-\-platform\fR> <\fB\-v\fR|\fB\-\-version\fR> [\fB\-h\fR|\fB\-\-help\fR] <\fIFILE\fR> 
.SH DESCRIPTION
Sign file and add to registry
.SH OPTIONS
.TP
\fB\-p\fR, \fB\-\-platform\fR \fI<PLATFORM>\fR
Target platform identifier
.TP
\fB\-v\fR, \fB\-\-version\fR \fI<VERSION>\fR
StartOS version number
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFILE\fR>
Path to the asset file
