.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-auth 1  "auth " 
.SH NAME
start\-tunnel\-auth \- Add or remove authorized clients
.SH SYNOPSIS
\fBstart\-tunnel auth\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Add or remove authorized clients
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-tunnel\-auth\-get\-pubkey(1)
Get the public key from the server
.TP
start\-tunnel\-auth\-key(1)
Commands for managing authorized keys
.TP
start\-tunnel\-auth\-login(1)
Login to a new auth session
.TP
start\-tunnel\-auth\-logout(1)
Logout from current auth session
.TP
start\-tunnel\-auth\-reset\-password(1)
Reset user interface password
.TP
start\-tunnel\-auth\-session(1)
List or kill auth sessions
.TP
start\-tunnel\-auth\-set\-password(1)
Set user interface password
