.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-db-dump 1  "dump " 
.SH NAME
start\-tunnel\-db\-dump \- Filter and query the database, display tables and records
.SH SYNOPSIS
\fBstart\-tunnel db dump\fR [\fB\-p\fR|\fB\-\-pointer\fR] [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIPATH\fR] 
.SH DESCRIPTION
Filter and query the database, display tables and records
.SH OPTIONS
.TP
\fB\-p\fR, \fB\-\-pointer\fR \fI<POINTER>\fR
JSON pointer to specific value
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIPATH\fR]
Path to the database file
