// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataUrl } from "./DataUrl"

export type CurrentDependencyInfo = {
  title: string | null
  icon: DataUrl | null
  versionRange: string
} & ({ kind: "exists" } | { kind: "running"; healthChecks: string[] })
