// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GatewayInfo } from "./GatewayInfo"
import type { IpHostname } from "./IpHostname"
import type { OnionHostname } from "./OnionHostname"

export type HostnameInfo =
  | { kind: "ip"; gateway: GatewayInfo; public: boolean; hostname: IpHostname }
  | { kind: "onion"; hostname: OnionHostname }
