// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcmeProvider } from "./AcmeProvider"
import type { GatewayId } from "./GatewayId"

export type PublicDomainConfig = {
  gateway: GatewayId
  acme: AcmeProvider | null
}
