// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionId } from "./ActionId";
import type { PackageId } from "./PackageId";

export type ActionParams = {
  id: PackageId;
  actionId: ActionId;
  input: { [key: string]: any } | null;
};
