// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BindOptions } from "./BindOptions";
import type { HostId } from "./HostId";

export type AddressInfo = { username: string | null, hostId: HostId, bindOptions: BindOptions, suffix: string, };