// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BindOptions } from "./BindOptions";

export interface AddressInfo { username: string | null, hostId: string, bindOptions: BindOptions, suffix: string, }