// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Alerts = { install: string | null, uninstall: string | null, restore: string | null, start: string | null, stop: string | null, };