// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupTargetId } from "./BackupTargetId";
import type { PackageId } from "./PackageId";
import type { PasswordType } from "./PasswordType";

export type BackupParams = {
  targetId: BackupTargetId;
  oldPassword: PasswordType | null;
  packageIds: Array<PackageId> | null;
  password: PasswordType;
};
