// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ChrootParams { env: string | null, workdir: string | null, user: string | null, path: string, command: string, args: string[], }