// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NotificationLevel } from "./NotificationLevel";
import type { PackageId } from "./PackageId";

export type CreateParams = {
  package: PackageId | null;
  level: NotificationLevel;
  title: string;
  message: string;
};
