// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataUrl } from "./DataUrl";

export type CurrentDependencyInfo = {
  title: string;
  icon: DataUrl;
  registryUrl: string;
  versionSpec: string;
  configSatisfied: boolean;
} & ({ kind: "exists" } | { kind: "running"; healthChecks: string[] });
