// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DependencyKind } from "./DependencyKind";

export interface DependencyRequirement { id: string, kind: DependencyKind, healthChecks: string[], }