// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportedHostnameInfo } from "./ExportedHostnameInfo";
import type { HostId } from "./HostId";
import type { HostKind } from "./HostKind";

export type ExportedHostInfo = {
  id: HostId;
  kind: HostKind;
  hostnames: Array<ExportedHostnameInfo>;
};
