// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExposedUI } from "./ExposedUI";

export type ExposeUiParams =
  | {
      type: "object";
      value: { [k: string]: ExposeUiParams };
    }
  | {
      type: "string";
      /** The path to the value in the Store. [JsonPath](https://jsonpath.com/)  */
      path: string;
      /** A human readable description or explanation of the value */
      description: string | null;
      /** (string/number only) Whether or not to mask the value, for example, when displaying a password */
      masked: boolean;
      /** (string/number only) Whether or not to include a button for copying the value to clipboard */
      copyable: boolean | null;
      /** (string/number only) Whether or not to include a button for displaying the value as a QR code */
      qr: boolean | null;
    };
