// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionMetadata } from "./ActionMetadata";

export interface ExportActionParams { id: string, metadata: ActionMetadata, }