// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExposedUI } from "./ExposedUI";

export interface ExposeUiParams { paths: Array<ExposedUI>, }