// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Callback } from "./Callback";

export type GetServiceInterfaceParams = {
  packageId: string | null;
  serviceInterfaceId: string;
  callback: Callback;
};
