// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HealthCheckString = "passing" | "disabled" | "starting" | "warning" | "failure";