// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MinMax } from "./MinMax";
import type { PackageId } from "./PackageId";

export type InstallParams = {
  id: PackageId;
  marketplaceUrl: string | null;
  versionSpec: string | null;
  versionPriority: MinMax | null;
};
