// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurrentDependencies } from "./CurrentDependencies";
import type { DataUrl } from "./DataUrl";
import type { HostInfo } from "./HostInfo";
import type { PackageState } from "./PackageState";
import type { Status } from "./Status";

export type PackageDataEntry = { stateInfo: PackageState, status: Status, marketplaceUrl: string | null, developerKey: string, icon: DataUrl, lastBackup: string | null, currentDependencies: CurrentDependencies, hosts: HostInfo, storeExposedDependents: string[], };