// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AllPackageData } from "./AllPackageData";
import type { ServerInfo } from "./ServerInfo";

export type Public = { serverInfo: ServerInfo, packageData: AllPackageData, ui: any, };