// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PasswordType } from "./PasswordType";

export type ResetPasswordParams = {
  oldPassword: PasswordType | null;
  newPassword: PasswordType | null;
};
