// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupTargetId } from "./BackupTargetId";
import type { PackageId } from "./PackageId";

export type RestorePackageParams = {
  ids: Array<PackageId>;
  targetId: BackupTargetId;
  password: string;
};
