// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddressInfo } from "./AddressInfo";
import type { ExportedHostInfo } from "./ExportedHostInfo";
import type { ServiceInterfaceId } from "./ServiceInterfaceId";
import type { ServiceInterfaceType } from "./ServiceInterfaceType";

export type ServiceInterfaceWithHostInfo = { hostInfo: ExportedHostInfo, id: ServiceInterfaceId, name: string, description: string, hasPrimary: boolean, disabled: boolean, masked: boolean, addressInfo: AddressInfo, type: ServiceInterfaceType, };