// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Duration } from "./Duration";

export type SetParams = {
  timeout: Duration | null;
  config: { [key: string]: any } | null;
};
