// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DependencyConfigErrors } from "./DependencyConfigErrors";
import type { MainStatus } from "./MainStatus";

export type Status = {
  configured: boolean;
  main: MainStatus;
  dependencyConfigErrors: DependencyConfigErrors;
};
