// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WgClientKind } from './WgClientKind'

export type AddDeviceParams = {
  subnet: string
  name: string
  ip: string | null
  /**
   * Client (no autoconfig) or Server (gateway-autoconfig on by default).
   */
  kind: WgClientKind
}
