// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DnsRecordEntry } from './DnsRecordEntry'

export type DnsRecords = Array<DnsRecordEntry>
