.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-auth-session 1  "session " 
.SH NAME
start\-tunnel\-auth\-session \- List or kill auth sessions
.SH SYNOPSIS
\fBstart\-tunnel auth session\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
List or kill auth sessions
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-tunnel\-auth\-session\-kill(1)
Terminate auth sessions
.TP
start\-tunnel\-auth\-session\-list(1)
Display all auth sessions
