.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-dns 1  "dns " 
.SH NAME
start\-tunnel\-dns \- View or edit injected DNS records
.SH SYNOPSIS
\fBstart\-tunnel dns\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
View or edit injected DNS records
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-tunnel\-dns\-add(1)
Add or replace a DNS record
.TP
start\-tunnel\-dns\-list(1)
List injected DNS records
.TP
start\-tunnel\-dns\-remove(1)
Remove a DNS record
