.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-device-remove 1  "remove " 
.SH NAME
start\-tunnel\-device\-remove \- Remove device from subnet
.SH SYNOPSIS
\fBstart\-tunnel device remove\fR [\fB\-h\fR|\fB\-\-help\fR] <\fISUBNET\fR> <\fIIP\fR> 
.SH DESCRIPTION
Remove device from subnet
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISUBNET\fR>

.TP
<\fIIP\fR>

