.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-auth-session-kill 1  "kill " 
.SH NAME
start\-tunnel\-auth\-session\-kill \- Terminate auth sessions
.SH SYNOPSIS
\fBstart\-tunnel auth session kill\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIIDS\fR] 
.SH DESCRIPTION
Terminate auth sessions
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIIDS\fR]
Session identifiers
