.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-subnet 1  "subnet " 
.SH NAME
start\-tunnel\-subnet \- Add, remove, or modify subnets
.SH SYNOPSIS
\fBstart\-tunnel subnet\fR [\fB\-h\fR|\fB\-\-help\fR] <\fISUBNET\fR> <\fIsubcommands\fR>
.SH DESCRIPTION
Add, remove, or modify subnets
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISUBNET\fR>

.SH SUBCOMMANDS
.TP
start\-tunnel\-subnet\-add(1)
Add a new subnet
.TP
start\-tunnel\-subnet\-remove(1)
Remove a subnet
