.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-dns-list 1  "list " 
.SH NAME
start\-tunnel\-dns\-list \- List injected DNS records
.SH SYNOPSIS
\fBstart\-tunnel dns list\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List injected DNS records
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
