.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-auth-reset-password 1  "reset-password " 
.SH NAME
start\-tunnel\-auth\-reset\-password \- Reset user interface password
.SH SYNOPSIS
\fBstart\-tunnel auth reset\-password\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Reset user interface password
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
