.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-update 1  "update " 
.SH NAME
start\-tunnel\-update
.SH SYNOPSIS
\fBstart\-tunnel update\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-tunnel\-update\-apply(1)
Apply available update
.TP
start\-tunnel\-update\-check(1)
Check for available updates
