.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-auth-key 1  "key " 
.SH NAME
start\-tunnel\-auth\-key
.SH SYNOPSIS
\fBstart\-tunnel auth key\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-tunnel\-auth\-key\-add(1)
Add a new authorized key
.TP
start\-tunnel\-auth\-key\-list(1)
List authorized keys
.TP
start\-tunnel\-auth\-key\-remove(1)
Remove authorized key
