.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-update-apply 1  "apply " 
.SH NAME
start\-tunnel\-update\-apply \- Apply available update
.SH SYNOPSIS
\fBstart\-tunnel update apply\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Apply available update
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
