.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-port-forward 1  "port-forward " 
.SH NAME
start\-tunnel\-port\-forward \- Commands for managing port forwards
.SH SYNOPSIS
\fBstart\-tunnel port\-forward\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Commands for managing port forwards
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-tunnel\-port\-forward\-add(1)
Add a new port forward
.TP
start\-tunnel\-port\-forward\-remove(1)
Remove port forward
.TP
start\-tunnel\-port\-forward\-set\-enabled(1)
Enable or disable a port forward
.TP
start\-tunnel\-port\-forward\-update\-label(1)
Update the label of a port forward
