.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-dns-remove 1  "remove " 
.SH NAME
start\-tunnel\-dns\-remove \- Remove a DNS record
.SH SYNOPSIS
\fBstart\-tunnel dns remove\fR [\fB\-\-type\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Remove a DNS record
.SH OPTIONS
.TP
\fB\-\-type\fR \fI<RTYPE>\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>

