.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-auth-logout 1  "logout " 
.SH NAME
start\-tunnel\-auth\-logout \- Logout from current auth session
.SH SYNOPSIS
\fBstart\-tunnel auth logout\fR [\fB\-h\fR|\fB\-\-help\fR] <\fISESSION\fR> 
.SH DESCRIPTION
Logout from current auth session
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISESSION\fR>

