// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GuaAccess } from './GuaAccess'
import type { HostnameInfo } from './HostnameInfo'

export type BindingSetGuaAccessParams = {
  internalPort: number
  address: HostnameInfo
  access: GuaAccess
}
