// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GuaAccess } from './GuaAccess'

export type BindingSetGuaAccessParams = {
  internalPort: number
  address: string
  access: GuaAccess
}
