// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostnameInfo } from './HostnameInfo'

export type BindingSetAddressEnabledParams = {
  internalPort: number
  address: HostnameInfo
  enabled: boolean | null
}
