// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BackupTargetId } from './BackupTargetId'

export type CifsUpdateParams = {
  id: BackupTargetId
  hostname: string
  path: string
  username: string
  password: string | null
}
