// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GuaAccess } from './GuaAccess'
import type { HostnameInfo } from './HostnameInfo'

export type DerivedAddressInfo = {
  /**
   * User override: enable these addresses (only for public IP & port)
   */
  enabled: Array<string>
  /**
   * User override: disable these addresses (only for domains and private IP & port)
   */
  disabled: Array<[string, number]>
  /**
   * User override: per-GUA exposure (only for IPv6 global-unicast addresses),
   * keyed by the GUA's `SocketAddrV6`. Absent ⇒ [`GuaAccess::Lan`].
   */
  guaAccess: { [key: string]: GuaAccess }
  /**
   * COMPUTED: NetServiceData::update — all possible addresses for this binding
   */
  available: Array<HostnameInfo>
}
