// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostId } from './HostId'
import type { ServiceInterfaceId } from './ServiceInterfaceId'

export type ExportRangeServiceInterfaceParams = {
  hostId: HostId
  internalStartPort: number
  id: ServiceInterfaceId
  name: string
  description: string
  scheme: string | null
}
