// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-GUA exposure chosen by the operator. Unlike every other address (an
 * on/off toggle), an IPv6 global-unicast address is a single globally-routable
 * address that can be reachable LAN-only or also from the WAN, so it carries a
 * tri-state:
 *
 * - `Disabled` — not bound / rejected.
 * - `Lan` (default) — reachable on-link, source-filtered to the gateway's
 *   subnet (traffic from outside the subnet is rejected). No WAN exposure.
 * - `LanWan` — also reachable from the WAN; the host attempts an IPv6 PCP
 *   pinhole on the gateway.
 *
 * Mirrors the WAN-opt-in posture of single-port public IPv4 (disabled by
 * default), but with an explicit LAN middle state because a GUA — unlike a
 * private LAN IP — is globally routable, so "on" must distinguish LAN-only
 * (firewalled) from WAN-exposed.
 */
export type GuaAccess = 'disabled' | 'lan' | 'lan-wan'
