// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NutSettings } from './NutSettings'

export type NutConfig = { enabled: boolean; settings: NutSettings | null }
