// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionId } from './ActionId'
import type { Guid } from './Guid'
import type { PackageId } from './PackageId'

export type RunActionParams = {
  packageId: PackageId
  eventId: Guid | null
  actionId: ActionId
  input?: any
}
