// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NutConfig } from './NutConfig'

export type SetNutParams = { config: NutConfig }
