// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionId } from './ActionId'
import type { PluginHostnameInfo } from './PluginHostnameInfo'

export type UrlPluginExportUrlParams = {
  hostnameInfo: PluginHostnameInfo
  removeAction: ActionId | null
  overflowActions: Array<ActionId>
}
