.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-container-subcontainer-destroy-fs 1  "destroy-fs " 
.SH NAME
start\-container\-subcontainer\-destroy\-fs
.SH SYNOPSIS
\fBstart\-container subcontainer destroy\-fs\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIGUID\fR> 
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIGUID\fR>

