.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-container-action-run 1  "run " 
.SH NAME
start\-container\-action\-run
.SH SYNOPSIS
\fBstart\-container action run\fR [\fB\-p\fR|\fB\-\-package\-id\fR] [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIACTION_ID\fR> <\fIINPUT\fR> 
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-p\fR, \fB\-\-package\-id\fR \fI<PACKAGE_ID>\fR
Package identifier
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIACTION_ID\fR>
Action identifier
.TP
<\fIINPUT\fR>
Input data for the action
