.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-net-gateway-set-name 1  "set-name " 
.SH NAME
start\-cli\-net\-gateway\-set\-name \- Rename a gateway
.SH SYNOPSIS
\fBstart\-cli net gateway set\-name\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIID\fR> <\fINAME\fR> 
.SH DESCRIPTION
Rename a gateway
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIID\fR>
Gateway identifier
.TP
<\fINAME\fR>
Name of the gateway
