.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-net-forward-dump-table 1  "dump-table " 
.SH NAME
start\-cli\-net\-forward\-dump\-table \- Dump port forward table
.SH SYNOPSIS
\fBstart\-cli net forward dump\-table\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Dump port forward table
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
