.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-net-vhost-remove-passthrough 1  "remove-passthrough " 
.SH NAME
start\-cli\-net\-vhost\-remove\-passthrough \- Remove vhost passthrough
.SH SYNOPSIS
\fBstart\-cli net vhost remove\-passthrough\fR <\fB\-\-hostname\fR> <\fB\-\-listen\-port\fR> [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Remove vhost passthrough
.SH OPTIONS
.TP
\fB\-\-hostname\fR \fI<HOSTNAME>\fR

.TP
\fB\-\-listen\-port\fR \fI<LISTEN_PORT>\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
