.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-wifi-add 1  "add " 
.SH NAME
start\-cli\-wifi\-add \- Add wifi ssid and password
.SH SYNOPSIS
\fBstart\-cli wifi add\fR [\fB\-h\fR|\fB\-\-help\fR] <\fISSID\fR> <\fIPASSWORD\fR> 
.SH DESCRIPTION
Add wifi ssid and password
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISSID\fR>
WiFi network SSID
.TP
<\fIPASSWORD\fR>
WiFi network password
