.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-registry-os-index 1  "index " 
.SH NAME
start\-cli\-registry\-os\-index \- List OS versions index
.SH SYNOPSIS
\fBstart\-cli registry os index\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List OS versions index
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
