.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-s9pk-select 1  "select " 
.SH NAME
start\-cli\-s9pk\-select \- Select the best compatible s9pk for a target device
.SH SYNOPSIS
\fBstart\-cli s9pk select\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIS9PKS\fR] 
.SH DESCRIPTION
Select the best compatible s9pk for a target device
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIS9PKS\fR]
Paths to s9pk package files
