.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-package-host-binding-list 1  "list " 
.SH NAME
start\-cli\-package\-host\-binding\-list \- List bindings for a host
.SH SYNOPSIS
\fBstart\-cli package host binding list\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List bindings for a host
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
