.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-wifi-country-set 1  "set " 
.SH NAME
start\-cli\-wifi\-country\-set \- Set the country
.SH SYNOPSIS
\fBstart\-cli wifi country set\fR [\fB\-h\fR|\fB\-\-help\fR] <\fICOUNTRY\fR> 
.SH DESCRIPTION
Set the country
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fICOUNTRY\fR>
ISO 3166\-1 alpha\-2 WiFi country code
