.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-tunnel-device-show-config 1  "show-config " 
.SH NAME
start\-cli\-tunnel\-device\-show\-config \- Show WireGuard configuration for device
.SH SYNOPSIS
\fBstart\-cli tunnel device show\-config\fR [\fB\-h\fR|\fB\-\-help\fR] <\fISUBNET\fR> <\fIIP\fR> [\fIWAN_ADDR\fR] 
.SH DESCRIPTION
Show WireGuard configuration for device
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISUBNET\fR>

.TP
<\fIIP\fR>

.TP
[\fIWAN_ADDR\fR]

