.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-notification-remove-before 1  "remove-before " 
.SH NAME
start\-cli\-notification\-remove\-before \- Remove notifications before a given ID
.SH SYNOPSIS
\fBstart\-cli notification remove\-before\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIBEFORE\fR> 
.SH DESCRIPTION
Remove notifications before a given ID
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIBEFORE\fR>
Get notifications before this ID
