.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-server-set-language 1  "set-language " 
.SH NAME
start\-cli\-server\-set\-language \- Set the system language
.SH SYNOPSIS
\fBstart\-cli server set\-language\fR [\fB\-h\fR|\fB\-\-help\fR] <\fILANGUAGE\fR> 
.SH DESCRIPTION
Set the system language
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fILANGUAGE\fR>
Language code
