.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-server-test-smtp 1  "test-smtp " 
.SH NAME
start\-cli\-server\-test\-smtp \- Test SMTP configuration
.SH SYNOPSIS
\fBstart\-cli server test\-smtp\fR <\fB\-\-host\fR> <\fB\-\-port\fR> <\fB\-\-from\fR> <\fB\-\-to\fR> <\fB\-\-username\fR> <\fB\-\-password\fR> <\fB\-\-security\fR> [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Test SMTP configuration
.SH OPTIONS
.TP
\fB\-\-host\fR \fI<HOST>\fR
SMTP server hostname
.TP
\fB\-\-port\fR \fI<PORT>\fR
SMTP server port
.TP
\fB\-\-from\fR \fI<FROM>\fR
Email sender address
.TP
\fB\-\-to\fR \fI<TO>\fR
Email recipient address
.TP
\fB\-\-username\fR \fI<USERNAME>\fR
SMTP authentication username
.TP
\fB\-\-password\fR \fI<PASSWORD>\fR
SMTP authentication password
.TP
\fB\-\-security\fR \fI<SECURITY>\fR
Connection security mode (starttls or tls)
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
starttls
.IP \(bu 2
tls
.RE
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
