.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-registry-os-asset-get 1  "get " 
.SH NAME
start\-cli\-registry\-os\-asset\-get \- Commands to download image, iso, or squashfs files
.SH SYNOPSIS
\fBstart\-cli registry os asset get\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Commands to download image, iso, or squashfs files
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-cli\-registry\-os\-asset\-get\-img(1)
Download IMG file
.TP
start\-cli\-registry\-os\-asset\-get\-iso(1)
Download ISO file
.TP
start\-cli\-registry\-os\-asset\-get\-squashfs(1)
Download squashfs file
