.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-notification-mark-seen-before 1  "mark-seen-before " 
.SH NAME
start\-cli\-notification\-mark\-seen\-before \- Mark notifications as seen before a given ID
.SH SYNOPSIS
\fBstart\-cli notification mark\-seen\-before\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIBEFORE\fR> 
.SH DESCRIPTION
Mark notifications as seen before a given ID
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIBEFORE\fR>
Get notifications before this ID
