.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-package-host-address-domain-private-add 1  "add " 
.SH NAME
start\-cli\-package\-host\-address\-domain\-private\-add \- Add a private domain to this host
.SH SYNOPSIS
\fBstart\-cli package host address domain private add\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIFQDN\fR> <\fIGATEWAY\fR> 
.SH DESCRIPTION
Add a private domain to this host
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFQDN\fR>
Fully qualified domain name
.TP
<\fIGATEWAY\fR>

