.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-cli-package-backup 1  "backup " 
.SH NAME
start\-cli\-package\-backup \- Commands for restoring package(s) from backup
.SH SYNOPSIS
\fBstart\-cli package backup\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Commands for restoring package(s) from backup
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
start\-cli\-package\-backup\-restore(1)
Restore packages from backup
