// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RangeBindInfo } from './RangeBindInfo'

export type BindingRanges = { [key: number]: RangeBindInfo }
