// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataUrl } from './DataUrl'
import type { LocaleString } from './LocaleString'

export type DependencyMetadata = {
  title: LocaleString | null
  icon: DataUrl | null
  description: LocaleString | null
  optional: boolean
}
