// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LshwDisplay = {
  product: string | null
  vendor: string | null
  capabilities: Array<string>
  driver: string | null
}
