// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PassthroughInfo = {
  hostname: string
  listenPort: number
  backend: string
  publicGateways: string[]
  privateIps: string[]
}
