// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DesiredStatus } from './DesiredStatus'
import type { ErrorData } from './ErrorData'
import type { HealthCheckId } from './HealthCheckId'
import type { NamedHealthCheckResult } from './NamedHealthCheckResult'

export type StatusInfo = {
  health: { [key: HealthCheckId]: NamedHealthCheckResult }
  error: ErrorData | null
  started: string | null
  desired: DesiredStatus
}
