// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignalStrength } from './SignalStrength'
import type { Ssid } from './Ssid'

export type WifiListOut = {
  ssid: Ssid
  strength: SignalStrength
  security: Array<string>
}
