.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-device-list 1  "list " 
.SH NAME
start\-tunnel\-device\-list \- List devices in a subnet
.SH SYNOPSIS
\fBstart\-tunnel device list\fR [\fB\-\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fISUBNET\fR> 
.SH DESCRIPTION
List devices in a subnet
.SH OPTIONS
.TP
\fB\-\-format\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISUBNET\fR>

