.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-auth-key-remove 1  "remove " 
.SH NAME
start\-tunnel\-auth\-key\-remove \- Remove authorized key
.SH SYNOPSIS
\fBstart\-tunnel auth key remove\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIKEY\fR> 
.SH DESCRIPTION
Remove authorized key
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIKEY\fR>

