.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH start-tunnel-device-set-dns-injection 1  "set-dns-injection " 
.SH NAME
start\-tunnel\-device\-set\-dns\-injection \- Allow or deny a device to inject DNS records
.SH SYNOPSIS
\fBstart\-tunnel device set\-dns\-injection\fR [\fB\-\-enabled\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fISUBNET\fR> <\fIIP\fR> 
.SH DESCRIPTION
Allow or deny a device to inject DNS records
.SH OPTIONS
.TP
\fB\-\-enabled\fR

.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISUBNET\fR>

.TP
<\fIIP\fR>

