name: Debian Package

on:
  workflow_call:
  workflow_dispatch:

env:
  NODEJS_VERSION: '18.15.0'
  ENVIRONMENT: "dev"

jobs:
  dpkg:
    name: Build dpkg
    strategy:
      fail-fast: false
      matrix:
        platform: [x86_64, x86_64-nonfree, aarch64, aarch64-nonfree, raspberrypi]
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        repository: Start9Labs/embassy-os-deb

    - uses: actions/checkout@v3
      with:
        submodules: recursive
        path: embassyos-0.3.x
    - run: |
        cp -r debian embassyos-0.3.x/
        VERSION=0.3.x ./control.sh
        cp embassyos-0.3.x/backend/embassyd.service embassyos-0.3.x/debian/embassyos.embassyd.service
        cp embassyos-0.3.x/backend/embassy-init.service embassyos-0.3.x/debian/embassyos.embassy-init.service
    
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODEJS_VERSION }}
    
    - name: Get npm cache directory
      id: npm-cache-dir
      run: |
        echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v3
      id: npm-cache
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: |
        echo "deb [arch=arm64] http://ports.ubuntu.com/ jammy main multiverse universe" | sudo tee -a /etc/apt/sources.list
        sudo dpkg --add-architecture arm64
        sudo apt-get update
        sudo apt-get install debmake debhelper-compat crossbuild-essential-arm64 libavahi-client-dev:arm64

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx        
      uses: docker/setup-buildx-action@v2

    - name: Run build
      run: "make VERSION=0.3.x TAG=${{ github.ref_name }}"
      env:
        OS_ARCH: ${{ matrix.platform }}

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.platform }}.deb
        path: embassyos_0.3.x-1_*.deb