name: PureOS Based ISO

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
    - master
    - next
    - feature/iso-ci

jobs:
  dpkg:
    uses: ./.github/workflows/debian.yaml

  iso:
    name: Build iso
    runs-on: ubuntu-22.04
    needs: [dpkg]
    steps:
    - uses: actions/checkout@v3
      with:
        repository: Start9Labs/eos-image-recipes

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y debspawn
        wget https://repo.pureos.net/pureos/pool/main/d/debootstrap/debootstrap_1.0.125pureos1_all.deb
        sudo apt-get install -y ./debootstrap_1.0.125pureos1_all.deb
        wget https://repo.pureos.net/pureos/pool/main/p/pureos-archive-keyring/pureos-archive-keyring_2021.11.0_all.deb
        sudo apt-get install -y ./pureos-archive-keyring_2021.11.0_all.deb

    - name: Configure debspawn
      run: |
        sudo mkdir -p /etc/debspawn/
        echo "AllowUnsafePermissions=true" | sudo tee /etc/debspawn/global.toml

    - uses: actions/cache@v3
      id: debspawn-cache
      with:
        path: /var/lib/debspawn
        key: ${{ runner.os }}-debspawn-byzantium

    - name: Make build container
      run: "debspawn list | grep byzantium-buildd-amd64 || debspawn create byzantium"

    - run: "mkdir -p overlays/vendor/root"

    - name: Download dpkg
      uses: actions/download-artifact@v3
      with:
        name: deb
        path: overlays/vendor/root

    - name: Run build
      run: './run-local-build.sh byzantium none custom "" true'

    - uses: actions/upload-artifact@v3
      with:
        name: iso
        path: results/*.iso
