name: Reusable Workflow

on:
  workflow_call:
    inputs:
      build_command:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
      artifact_path:
        required: true
        type: string

jobs:
  generic_build_job:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Docker Buildx        
      uses: docker/setup-buildx-action@v1

    - name: Build image
      run: ${{ inputs.build_command }}

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.artifact_path }}
