name: Automated Tests

on:
  push:
    branches:
      - master
      - next/*
  pull_request:
    branches:
      - master
      - next/*

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  NODEJS_VERSION: "24.11.0"
  ENVIRONMENT: dev-unstable

jobs:
  test:
    name: Run Automated Tests
    if: github.event.pull_request.draft != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: ./.github/actions/setup-build
        with:
          nodejs-version: ${{ env.NODEJS_VERSION }}
          free-space: "false"
          setup-docker: "false"
          setup-sccache: "false"

      - name: Build And Run Tests
        run: make test
